/* ==========================================================================
   rami.party: Realm registry
   --------------------------------------------------------------------------
   The single source of truth for every realm shown on the hub.

   • RAMI_GROUPS  → the three great realms (categories), rendered in order.
   • RAMI_REALMS  → individual portals. Set `category` to a group id.

   ➕ To add a project: append one object to RAMI_REALMS. Order within a group
      = ranking (top of the array shows first). Nothing else to touch.
      status: 'live' (clickable) · 'soon' (locked teaser)
      external: true opens in a new tab and shows an ↗ marker.
      search: a plain, keyword-rich description used ONLY by the on-site search
              (never displayed): write the real, boring explanation here so
              projects are findable without knowing the whimsical copy.
   ========================================================================== */

window.RAMI_GROUPS = [
    {
        id: 'gallery',
        emoji: '🏛️',
        title: 'The Gallery of Wonders (Completed projects)',
        blurb: 'Finished realms, polished and ready to explore.',
    },
    {
        id: 'workshop',
        emoji: '⚗️',
        title: 'The Workshop (Work in progress)',
        blurb: 'Spells still being brewed: works in progress & playthings.',
    },
    {
        id: 'wastes',
        emoji: '☄️',
        title: 'The Wastelands (Abandoned or old projects)',
        blurb: 'Fallen, forgotten and abandoned experiments. Enter the ruins.',
    },
];

window.RAMI_REALMS = [
    /* ---- The Gallery of Wonders (finished) ---- */
    {
        category: 'gallery',
        title: 'Labidi.eu',
        href: 'https://labidi.eu/',
        glyph: '✨',
        tagline: 'The professional shelf',
        description: 'All the cool, decent and professional projects that outgrew the playground now live together at labidi.eu: survival guides, radars, detectors, studios and more.',
        search: 'The professional project portfolio at labidi.eu. Home of every finished project that graduated from rami.party: OASIS the offline air-gapped survival guide at oasis.labidi.eu, GhostTooth the Bluetooth AirTag and tracker radar at ghosttooth.labidi.eu, the Phonetic Codex NATO spelling alphabet studio at alphabet.labidi.eu, TapFate the random first player picker at tapfate.labidi.eu, Breachlight incident response triage at breach.labidi.eu, Mail Ward SPF DKIM DMARC email authentication at mail.labidi.eu, the Markdown Scribe editor at md.labidi.eu, The People Library personality workshops at library.labidi.eu, Daily Board notes and tasks at todo.labidi.eu, and Huiskeuring home inspection at huiskeuring.be.',
        tags: ['portfolio', 'professional'],
        aura: 'gold',
        status: 'live',
        external: true,
    },
    {
        category: 'gallery',
        title: 'Lore Gallery',
        href: './gallery/lore/',
        glyph: '📜',
        tagline: 'A grimoire of images',
        description: 'Leaf through a living grimoire of magical lore, muggle mischief and impossibly cute creatures.',
        search: 'An image gallery of fantasy and Harry Potter themed artwork, magical creatures, wizards and humorous memes. Browse and view a curated picture collection of magic art and cute animals.',
        tags: ['gallery', 'magic'],
        aura: 'violet',
        status: 'live',
    },
    {
        category: 'gallery',
        title: 'Tasks for unlocked computers',
        href: './gallery/prankscreens/',
        glyph: '🔓',
        tagline: 'They left it unlocked',
        description: 'Someone walked away without pressing Win+L. Three ways to mark the occasion: cast a full-screen illusion, send the traditional BBQ confession mail, or run a harmless reversible desktop prank.',
        search: 'What to do when a colleague leaves their computer unlocked and walks away. Three options: fake full-screen illusions including fake operating system boot screens, fake Windows and macOS and Android update screens, fake BIOS flash screens, blue black and purple screens of death, fake ransomware and hacked hacker terminal screens; the office BBQ tax confession email that sends a funny joke mail admitting they forgot to lock their PC; and a toolkit of harmless reversible desktop pranks with PowerShell, Command Prompt and keyboard shortcuts, each with an undo. Also known as prank screens, unlocked computer punishment, and the Win+L tradition.',
        tags: ['prank', 'fullscreen', 'office'],
        aura: 'cyan',
        status: 'live',
    },

    /* ---- The Wastelands (archived / fallen) ---- */
    {
        category: 'wastes',
        title: 'Neko Paradise',
        href: './wasteland/neko/',
        glyph: '🐱',
        tagline: 'A clowder of sprites',
        description: 'A mischievous clowder of chibi neko familiars, retired to the ruins, but still purring.',
        search: 'An interactive toy with draggable chibi cat sprites (neko). A cute cats animation playground. Archived and retired.',
        tags: ['toy', 'cats'],
        aura: 'ash',
        status: 'live',
    },
    {
        category: 'wastes',
        title: 'Old rami.party',
        href: './wasteland/old-rami.party/',
        glyph: '🏚️',
        tagline: 'The jQuery era',
        description: 'The previous incarnation of this domain, a paws-and-cats relic, preserved as it was found.',
        search: 'The previous old version of the rami.party website, built with jQuery and cat themed. Archived legacy website preserved as it was.',
        tags: ['legacy', 'jquery'],
        aura: 'ash',
        status: 'live',
    },
    {
        category: 'wastes',
        title: 'ADHD experiment',
        href: '#',
        glyph: '🌀',
        tagline: 'Never drew breath',
        description: 'An empty husk, a project that was conjured but never filled. A reminder that not every spell takes.',
        search: 'An empty, abandoned and dropped project folder that was never built or finished. Placeholder that never drew breath.',
        tags: ['empty'],
        aura: 'ash',
        status: 'soon',
    },
    {
        category: 'wastes',
        title: 'Daybook',
        href: './workshop/todo/',
        glyph: '🗒️',
        tagline: 'Followed up by Daily Board',
        description: 'The calm offline notes-and-to-do companion, retired with honours. Followed up by Daily Board · Notes & tasks at todo.labidi.eu.',
        search: 'A clean minimal notes and todo list app. Write notes and manage a checklist of tasks that autosave to localStorage in the browser, with dark mode, timestamps, a new day reset that archives yesterday and keeps unfinished tasks. Archived; its successor is Daily Board notes and tasks at todo.labidi.eu.',
        tags: ['tool', 'legacy'],
        aura: 'ash',
        status: 'live',
    },
    {
        category: 'wastes',
        title: 'Notes & Todo',
        href: './wasteland/notes/',
        glyph: '🗒️',
        tagline: 'Twice reborn',
        description: 'The original plain notes-and-todo scratchpad. Its descendant Daybook now rests beside it in the ruins; the living heir is Daily Board at todo.labidi.eu.',
        search: 'The original simple notes and todo list page with autosaving notes, a checklist, dark mode and a new day reset. Archived and succeeded by Daybook and then Daily Board at todo.labidi.eu.',
        tags: ['tool', 'legacy'],
        aura: 'ash',
        status: 'live',
    },
];

/* ==========================================================================
   The Workshop catalogue
   --------------------------------------------------------------------------
   Rendered on /workshop/ (see workshop/index.html). These are the works in
   progress; each lives in its own folder under /workshop/<name>/.

   ➕ To add a workshop project: drop its folder in /workshop/ and append an
      object here. Order within the array = ranking (top shows first).
      status: 'live' (clickable) · 'soon' (locked teaser).
   ========================================================================== */
window.RAMI_WORKSHOP = [
    {
        title: 'Glamours',
        href: './glamours/',
        glyph: '🪄',
        tagline: 'Re-enchant other people\u2019s websites',
        description: 'A spellbook of small userscripts and userstyles that fix the web apps you are stuck with. Truesight shows every host, IP and browser API a page reaches for. Prism repaints and rescales any site until it is readable. Plus a comfort glamour and a ticket autopilot for ConnectWise Manage. Each one also runs as a bookmarklet.',
        search: 'A collection of Tampermonkey userscripts and Stylus userstyles that improve and customize third party websites with custom CSS and JavaScript, each one also available as a drag to bookmarks bar bookmarklet that needs no browser extension. Truesight is a page inspector for incident response, security analysis, phishing triage and privacy investigation that shows every domain, hostname and IP address a web page connects to, separating first party from third party, catching fetch, XMLHttpRequest, sendBeacon, WebSocket, EventSource, images, scripts and stylesheets through wrapped APIs and the resource timing PerformanceObserver, flagging mixed content, requests straight to an IP address, password forms that post to another domain or over http, links whose text does not match their destination, cross origin iframes without a sandbox, tracking pixels, hidden inputs, code built at runtime with new Function, timers given strings to execute, and WebRTC ICE candidate IP address leaks, listing cookies, localStorage, sessionStorage and IndexedDB, with x-ray overlays that outline frames and reveal hidden elements, a hold the page button that strips meta refresh and blocks window.open to stop a redirect chain, and a copy report button that produces a Markdown indicator of compromise report for a ticket, all offline with nothing sent anywhere. Prism is a reading comfort and accessibility tool for any website that inverts the page or repaints it in a dark, sepia, high contrast or custom colour theme, scales text size from 70 to 200 percent without browser zoom so layout boxes keep their size, adjusts line height, letter spacing and line length, overrides the font with a high legibility face, underlines links, stops animations and dims or hides images, remembered per site. Includes a ConnectWise Manage PSA comfort glamour for myconnectwise.net, every regional tenant including eu, na and au, with six themes, four dark mode themes plus a pale vivid high saturation theme and a soft greyscale monochrome theme, an option to darken the left menu bar, a hover ticket preview tooltip that shows the full truncated grid row without opening the ticket with a picker for which columns appear such as date entered, entered by, updated by and service board, plus the ticket content with the note count, last note author and note text, highlighting of stale tickets with no update for five days in red amber or violet, automatically setting Subtype and Item to Change when the Type is Change, a password manager friendly login with autocomplete fixed and auto fill of company and username, a caps lock warning, and true text only scaling that enlarges fonts without zooming the whole page. Also a ConnectWise Manage ticket autopilot that automatically sets ticket fields as each ticket is opened during triage: stamping every ticket with a chosen Board, Status, Type, Subtype and Item applied in that dependency order because the board decides which statuses and types exist, setting the service priority, and filling a due date a chosen number of days or months out while skipping weekends, with the Type, Subtype, Item and Status dropdown lists built into the script, a Run autopilot button added to the ticket toolbar so a single click applies the lot to just that ticket, a log of every field it changed, an only fill empty fields safety default, and a countdown timer that switches the whole thing off by itself after fifteen minutes to eight hours so a triage rule cannot be left running by accident. Compares the userscript managers Greasemonkey, Tampermonkey, Violentmonkey and FireMonkey and explains the differences, plus how to enable the Allow User Scripts permission or Developer Mode in Chrome and Edge, and every alternative: Stylus userstyles, bookmarklets, DevTools local overrides, uBlock Origin cosmetic filters, Firefox userContent.css and per site browser zoom.',
        tags: ['userscript', 'css', 'tool'],
        aura: 'violet',
        status: 'live',
    },
    {
        title: 'Chronoport',
        href: './chronoport/',
        glyph: '⏳',
        tagline: 'A gateway from the year 3050',
        description: 'A time traveller’s console: the world’s clocks at a glance, the Sun and Moon above your exact spot, twilight ledgers, sidereal time and a countdown to the 31st century, all computed on your own device.',
        search: 'A world clock and time zone dashboard showing the current time across the world in major cities, plus sunrise, sunset, solar noon, day length, civil nautical and astronomical twilight and golden hour times for your own location, and the current sun altitude and azimuth. Also shows the moon phase, moon illumination percentage, moon age, moonrise and moonset, lunar distance and the next full moon and new moon. Includes the Unix epoch timestamp, ISO 8601 time, Julian date and modified Julian date, local sidereal time, day of year, ISO week number, Swatch internet beat time, decimal and hexadecimal time, GPS week, equation of time, true solar sundial time, equinox and solstice dates, Earth orbital speed and distance to the Sun, a relativistic time dilation and Lorentz factor calculator, and a countdown to the year 3050. Works offline with no API, geolocation optional.',
        tags: ['clock', 'astronomy'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Interview Forge',
        href: './interview-forge/',
        glyph: '🎙️',
        tagline: 'Run a better interview',
        description: 'A calm, professional companion for job interviews: a guided setup or a one-click quick start, a searchable bank of hundreds of questions with the model answer one click away, a DISC list, split-screen note taking, a Markdown or PDF report and a side-by-side comparison of every candidate. Dutch, English and French, six themes, entirely offline.',
        search: 'An interview tool, interview guide and question bank for interviewers, hiring managers, recruiters and HR during a job application or solicitation. Guided setup wizard or quick start: fill in the candidate details, attach the CV or PDF you got from HR, pick a position or job profile such as IT service desk agent, second line support engineer, field technician, digital workplace consultant, Microsoft Office application support, service desk team lead, network and firewall engineer, networking and switching junior, firewall expert, Windows system engineer, Linux system engineer, virtualisation engineer, Microsoft Azure engineer, Microsoft 365 engineer, cloud architect, basic IT troubleshooting, security engineer, SOC analyst, pentester or ethical hacker, GRC and compliance officer, software developer, front-end developer, back-end developer, DevOps engineer, data analyst, AI and machine learning engineer, database administrator, project and delivery manager, scrum master, customer success manager, account manager, marketing assistant, marketing manager, HR officer, recruiter, IT consultant, team lead, office manager or intern. Selecting a position automatically ticks the matching subjects and skill areas, which you can change yourself and save as a template or share with a link. Starter templates keep the list short for beginners. Hundreds of trilingual interview questions with the correct answer hidden behind a button so the interviewer can check it: what is the difference between TCP and UDP, what happens if DNS does not reply, what happens if a device has no default gateway, what does BGP stand for and what does it do, what is DHCP, what are SPF DKIM and DMARC, what is a NAT rule, have you updated a SonicWall, which hypervisors have you used, VLANs, spanning tree, subnetting, TLS certificates, IPsec and SSL VPN, zero trust, conditional access, Intune, Active Directory, Kerberos, PowerShell, Linux permissions, backup and RAID, containers, CI/CD, SQL, OWASP, phishing and ransomware response, ITIL incident problem and change, plus behavioural and personality questions such as can you work in a team and have you been a team leader before, and a full DISC question list to estimate the red, yellow, green and blue colours. Take notes underneath every question while the candidate talks, rate each answer, use tabs or a split book view with the questions on one side and your notes on the other, then export a Markdown or PDF report of only the fields you filled in, only the questions you annotated, or everything. Compare all interviewed candidates side by side per subject. Available in Dutch, English and French with multiple themes; everything stays in the browser.',
        tags: ['tool', 'hr', 'interview', 'guide'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'IT Tools Workbench',
        href: './tools/',
        glyph: '🧰',
        tagline: 'A curated bench of IT tools',
        description: 'A hand-curated, searchable toolkit of 200+ IT tools: network, security, development and system utilities, the Microsoft admin portal maze, plus a few tools hosted right here.',
        search: 'An IT toolkit and curated collection of information technology tools and resources: network, security, development, system utilities, forensics, self-hosting, Microsoft portals, DNS and hosting and more. Searchable and filterable by topic, type (online, download, browser extension), free only and GDPR. Includes locally hosted tools such as a weekly CVE checker and CyberChef.',
        tags: ['tool', 'reference'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Rami\u2019s Open Source Toolkit',
        href: './opensource/',
        glyph: '🧭',
        tagline: 'One search across the whole bench',
        description: 'Every tool, every thing worth reading, every search engine and every European event in one searchable list, sorted into nineteen plain subjects. Pick a subject on the left, or just start typing. Meant to replace the IT Toolkit and the IT News Scroll.',
        search: 'A single searchable catalogue of 704 curated entries: IT tools, learning and news resources, vendor security advisory and PSIRT pages, search engines of every kind, and conferences and hacker camps. Three shelves (tools, reading, events) and nineteen shared subjects: security, incident response, OSINT and forensics, search engines, network, system and Windows, Microsoft and cloud, development, open source and Linux, self-hosting, learning, labs and CTF, podcasts and video and newsletters, communities, Belgium and the EU, media and creative, office and notes, AI assistants and browser extensions. The search engine collection covers general web search (Google, Bing, DuckDuckGo, Yahoo, Brave Search, Startpage, Ecosia, Qwant, Mojeek, Marginalia, Wiby, Kagi, Lycos), regional engines (Yandex, Baidu, Naver, Seznam), metasearch and self-hosted search (SearXNG, MetaGer, Swisscows), AI answer engines (Perplexity, You.com, Phind), news and monitoring (Google News, Google Alerts, Google Trends, Google Dataset Search), reverse image and visual search (Google Images, Google Lens, Bing Visual Search, Yandex Images, TinEye, Baidu Images, Copyseeker, SauceNAO, ImgOps, PimEyes face search), media and licensing search (Openverse, Wikimedia Commons, Unsplash, Pexels, Pixabay, YouTube, Invidious, Listen Notes), code and developer search (GitHub code search, grep.app, Sourcegraph, SearchCode, PublicWWW, Stack Overflow, DevDocs, npm, PyPI, Maven Central, NuGet, crates.io, pkg.go.dev, Packagist, RubyGems, Docker Hub), academic and reference search (Google Scholar, Semantic Scholar, OpenAlex, BASE, CORE, PubMed, arXiv, RefSeek, Wolfram Alpha, Google Patents, Espacenet), archives and books (Internet Archive, Wayback Machine, Open Library, Google Books, HathiTrust, Europeana, Common Crawl), people and social search (Namechk, WhatsMyName, That\u2019s Them, Social Searcher, X advanced search, Reddit, Bluesky, Mastodon), company and sanctions registers (OpenCorporates, Companies House, EU business registers, GLEIF LEI, OpenSanctions, OCCRP Aleph), internet scan engines (Shodan, Censys, ZoomEye, FOFA, ONYPHE, Netlas, LeakIX, Criminal IP, GreyNoise, AlienVault OTX), technology profiling with BuiltWith and AlternativeTo, package and vulnerability search (Repology, pkgs.org, Vulners, CVE Details, OSV), Tor search with Ahmia, and Google dorking with the Google Hacking Database. Filter by how a tool runs (online, online plus app, download, browser extension), by access (open or account needed), by event type (conference, hacker camp, CTF contest, trade fair, training, meetup), by country or region, free only, still to come, and entries that link to a public source repository on GitHub, GitLab, Codeberg or SourceForge. Card and list views, relevance search, shareable URL state, and a subject rail with live counts. The catalogue is thirty-five small plain data files, one per shelf and subject, so adding an entry means appending one object.',
        tags: ['tool', 'reference', 'search'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Frostcaller',
        href: './frostcaller/',
        glyph: '❄️',
        tagline: 'Bewitch the air conditioner',
        description: 'A beginner’s guide to building your own infrared blaster so Home Assistant can switch the air conditioning on and off, no soldering, from about €5. Tick the parts you own, follow the path that fits, then talk to the board straight from your browser.',
        search: 'A beginner friendly DIY guide and tutorial for building a cheap Wi-Fi infrared IR blaster or IR remote to control an air conditioner, air conditioning unit or heat pump from Home Assistant, with no soldering required. Interactive what parts do you have inventory picker: tick the components you already own and it shows which build paths are ready, what is still missing and what it costs, saved between visits and shareable as a permalink. Six paths: ESPHome with an ESP32, ESP8266, Wemos D1 mini, M5Stack Atom Lite or M5StickC and a KY-005 IR transmitter LED module wired with dupont jumper wires; a ready made Athom blaster with ESPHome pre-installed; re-flashing a cheap Tuya or Moes Wi-Fi IR blaster with tuya-cloudcutter, ltchiptool and LibreTiny; the Broadlink RM4 Mini with the native Home Assistant integration and SmartIR; and a UFO-R11 Zigbee IR blaster with Zigbee2MQTT. Includes an ESPHome YAML config generator and builder that writes the finished configuration file for your board, pin and air conditioner brand and lets you download it. Fully built buy and forget options compared: Athom, Broadlink, SwitchBot Hub 2, Xiaomi Mi smart remote, Sensibo, Tado and Nature Remo, rated local versus cloud. Software bench with download links and guides for Home Assistant, ESPHome Builder, ESPHome Web, the Arduino IDE, the IRremoteESP8266 library, PlatformIO, Tasmota and its web installer, esptool, HACS, SmartIR and Zigbee2MQTT, plus six different ways to flash or write the firmware including a complete Arduino sketch. Includes the ESPHome climate_ir brand table (coolix, daikin, LG, midea, mitsubishi, gree, toshiba, tcl112, fujitsu, whirlpool, heatpumpir), remote_transmitter and remote_receiver YAML, how to capture and replay raw IR codes from your own remote, infrared line of sight and range advice, and extras such as room temperature sensors, knowing whether the AC is really running, presence and window automations, sleep ramps, controlling the TV, Alexa Google and Siri, notifications, running costs, troubleshooting and safety. Full text search across the guide, a printable version, a copyable shopping list with price search links, live currency conversion and four colour themes including a light and a high contrast one. Also includes a side by side comparison of every path, a what went wrong troubleshooting wizard, a pin map showing which GPIO pins are safe on the ESP32, ESP8266 and ESP32-C3, a log reader that explains ESPHome and Tasmota log lines, a raw infrared code toolbox that converts captured timings into ESPHome buttons and Pronto codes, a running cost estimator, a QR code and Markdown export, keyboard shortcuts and offline support. A companion Web Serial page called The Scribe connects to the board over USB from the browser to identify the chip, watch the live serial log, capture infrared codes from your remote and send Tasmota IRHVAC commands, with no drivers or serial monitor to install.',
        tags: ['guide', 'smart home'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Loregate',
        href: './dm-screen/',
        glyph: '🐉',
        tagline: 'Dual-screen DM table',
        description: 'A Dungeon Master\u2019s command table for tabletop RPGs: build battlemaps with painted terrain, props and pre-made locations, move tokens, sculpt fog of war, run initiative and the big bad, all mirrored live onto a second screen for your players.',
        search: 'A Dungeon Master screen and virtual tabletop for Dungeons and Dragons and other tabletop RPGs. Two screens: a DM control page and a separate player map page for an external monitor or TV. Build multiple saved locations, paint realistic terrain (grass, stone, water, lava, snow) cell by cell, place and drag props and items like chests doors traps torches and mimics, choose which items and creatures are visible to players, move player and monster tokens on a battlemap grid, paint fog of war and dynamic light to reveal the map, track hit points armour class conditions and initiative turn order, resize the big bad boss, keep a bestiary and a party inventory, roll dice, use pre-generated maps (tavern, fields, cavern, traps and treasure, mimic hall), a party HP sidebar for players, weather and animation effects, and export or import the whole campaign. Live synced between both screens, runs locally in the browser.',
        tags: ['app', 'ttrpg'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Spectrum Scryer',
        href: './spectrum-scryer/',
        glyph: '📡',
        tagline: 'Every Wi-Fi around you',
        description: 'Reveal every access point in the neighbourhood, hidden ones included, chart the 2.4, 5 and 6 GHz bands, listen for Bluetooth neighbours and let the locator walk you to any signal.',
        search: 'A WiFi scanner, wireless network analyser and channel map that shows all wifi access points and networks in the neighbourhood, including hidden SSID networks that broadcast no name. Paste the output of netsh wlan show networks, nmcli device wifi list, iw scan, iwlist scan or the macOS airport command and it parses every BSSID, MAC address, vendor, channel, frequency, band, channel width, encryption and signal strength in dBm or percent. Shows 2.4 GHz, 5 GHz and 6 GHz band usage with an overlap chart and best channel advice for reducing interference, plus a signal locator and direction finder that estimates distance from RSSI to help you find a router, rogue access point or hidden network. Also scans nearby Bluetooth and BLE devices on 2.4 GHz and reports the current connection type and speed. Exports scans as JSON or CSV, runs entirely offline in the browser.',
        tags: ['network', 'tool'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Sixth Sense',
        href: './sixth-sense/',
        glyph: '🔮',
        tagline: 'Detect the undetectable',
        description: 'A séance for your phone: it wakes every sensor the device will admit to: motion, gyroscope, magnetometer, light, microphone, camera, radios, then watches for the tremors, fields and frequencies you can neither feel nor hear.',
        search: 'A device sensor test and diagnostics page that detects and lists every sensor and hardware API available in the browser: accelerometer, gyroscope, magnetometer and compass, ambient light sensor, proximity sensor, GPS geolocation, microphone, camera, battery status, network information, vibration haptics, Bluetooth, NFC, USB, serial, HID, gamepad, WebXR, WebGPU, screen orientation and display info. Shows live readings, an EMF-meter style magnetic field monitor, a seismograph-like micro vibration and tremor detector, infrasound and ultrasound detection from the microphone, invisible infrared light and mains flicker detection through the camera, and an anomaly meter with baseline calibration. Also a timestamped event log, beep and vibration alerts, sound level in dBFS, a screen wake lock so the phone stays awake while monitoring, and a downloadable or copyable JSON diagnostics report. Runs locally in the browser with no data sent anywhere.',
        tags: ['sensors', 'hardware', 'tool'],
        aura: 'violet',
        status: 'live',
    },
    {
        title: 'Echo',
        href: './batlistener/',
        glyph: '🦇',
        tagline: 'Bat-sound listener',
        description: 'Point your microphone at the night and Echo watches the top of the audible band for bat-like clicks and chirps: capturing calls, replaying them aloud, or letting you study the waveforms in silence.',
        search: 'A bat sound detector and listener that uses the device microphone and the Web Audio API to watch for high-frequency ultrasonic bat calls, clicks and chirps. Shows a live spectrogram, captures and records detected calls, plays them out loud, and lets you view the soundwaves and waveforms without playing the sound. Runs locally in the browser.',
        tags: ['audio', 'tool'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Personal Trainer Forge',
        href: './trainer-forge/',
        glyph: '💪',
        tagline: 'A plan that knows the date',
        description: 'Answer six questions and walk away with a real training block: rest days, weekly progression and deload weeks included. From five minutes a day to a full gym session, and every day is yours to change.',
        search: 'A free custom workout plan generator and training program builder. Choose a goal: strength without getting bulky with calisthenics, hypertrophy for bigger arms and back, running further and building stamina and endurance, fat loss and conditioning, mobility and posture, all-round health, or short 5, 10 and 15 minute movement snacks and micro workouts for people with no time, then set your days per week, session length in minutes, available equipment (bodyweight, pull-up bar, resistance bands, dumbbells or a full gym) and the muscles you want to focus on. Generates a day by day workout schedule with warm-ups, sets, reps, rest times, RPE, rest days, progressive overload and deload weeks. Swap any single exercise you do not like, turn any training day into a rest day, or drop a quick 10 minute session in instead. Includes a 140 exercise library with coaching cues and easier or harder variations, day-aware today view with days remaining, session logging, shareable links, JSON export and import, and printable PDF plans. Push pull legs, upper lower and full body splits, desk reset and morning mobility routines, couch to 5k style run walk progressions and interval, tempo and long run sessions.',
        tags: ['app', 'fitness'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Isekai Forge',
        href: './character-forge/',
        glyph: '🎲',
        tagline: 'Roll a whole hero',
        description: 'A one-tap character and background roller for other-world stories: how they got dragged in, who they used to be, the power they woke up with and the world that caught them. Reroll one line or shuffle an entire destiny.',
        search: 'A random character generator and creator for isekai and reincarnation stories. Shuffles and randomizes a background and character: how they were transported or isekaid, their past life, the being they were reborn as, the ability or power they gained, and the world they landed in. Reroll each part individually or shuffle everything at once.',
        tags: ['toy', 'generator'],
        aura: 'pink',
        status: 'live',
    },
    {
        title: 'Demoscene Generator',
        href: './demoscene-forge/',
        glyph: '🌈',
        tagline: 'Conjure video & music',
        description: 'A retro-futuristic forge for short demoscene visuals and chiptune music: shapes, plasma, kaleidoscopes and a WebAudio synth, exportable to video & audio.',
        search: 'A browser based demoscene video and music generator. Create animated visuals with shapes, plasma, kaleidoscope, glow, scanlines and CRT effects plus a chiptune music synthesizer, then export to video and audio. Built with Canvas, WebAudio and MediaRecorder.',
        tags: ['demoscene', 'canvas', 'audio'],
        aura: 'violet',
        status: 'live',
    },
    {
        title: '3D Forge',
        href: './3d-forge/',
        glyph: '🧊',
        tagline: 'Text & pics → 3D prints',
        description: 'Turn text, emoji, shapes, QR codes and photos into watertight, 3D-printable models. Export as STL, 3MF, OBJ, PLY or AMF.',
        search: 'A 3D model generator that converts text, emoji, shapes, QR codes and photos into watertight 3D printable models and meshes, exportable as STL, 3MF, OBJ, PLY and AMF files for 3D printing.',
        tags: ['tool', '3d'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'D&D Forge',
        href: './dnd-forge/',
        glyph: '🐉',
        tagline: 'Forge a whole hero',
        description: 'A full Dungeons &amp; Dragons character builder across six editions: a nine-step wizard, a live sheet, a dice roller, backstory weaving, a DM’s Charter and a party muster board.',
        search: 'A Dungeons and Dragons character creator, builder and generator for 5E 2024, 5E 2014, 3.5, 4E, AD&D 2E and AD&D 1E. Roll or point-buy ability scores, choose race species class subclass background skills feats weapons armour equipment and spells, with automatic calculation of hit points armour class proficiency bonus saving throws spell slots and spell save DC. Includes a random surprise me character generator, a fantasy name generator, a backstory weaver, a floating dice roller with advantage and disadvantage, printable character sheet, JSON export and import, shareable links, a seedable fate seed, a DM charter to lock table rules, a play mode character file with HP damage healing conditions and death saves, and a DM muster page to assemble the party.',
        tags: ['app', 'ttrpg'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Webcheck',
        href: './webcheck/',
        glyph: '🔍',
        tagline: 'Website audit oracle',
        description: 'Scry any site for robots.txt, sitemaps, security.txt, favicons and meta-runes, then reveal what is missing.',
        search: 'A website audit and SEO checker tool. Scans a website for robots.txt, sitemap.xml, security.txt, favicons and meta tags and reports what is present or missing.',
        tags: ['tool', 'seo'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Tremorbell',
        href: './tremorbell/',
        glyph: '🔔',
        tagline: 'A pocket seismograph',
        description: 'Turn your phone or laptop into a friendly seismograph. Every wobble is drawn as a live trace and turned into a Richter-style local magnitude, with the shaking intensity people would actually feel.',
        search: 'An earthquake detector and seismograph in the browser that uses the device motion sensors and accelerometer to measure shaking, movement and vibration and converts it into a Richter scale local magnitude, peak ground acceleration in gal and Modified Mercalli felt intensity. Shows a live seismograph trace, a Richter magnitude gauge, a tremor event log with CSV export, adjustable trigger threshold and epicentre distance, a demo quake simulation for devices without sensors, and cute pastel themes including a dark and a high contrast one. Runs locally in the browser.',
        tags: ['sensor', 'tool'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Clamor',
        href: './decibel/',
        glyph: '🔊',
        tagline: 'How loud is it here?',
        description: 'Point your microphone at the room and watch the decibels climb: a live meter with peak, average and Leq readings, a rolling history graph, and an alarm that shouts back when the noise crosses your line.',
        search: 'A sound level meter, decibel meter and noise meter that uses the device microphone and the Web Audio API to measure how loud the sound around you is in dB SPL. Shows a live A-weighted decibel readout, upper limits with peak, maximum, minimum, average and Leq statistics, a 60 second history graph, calibration and fast slow impulse response settings, and a configurable loudness alarm with a beep, screen flash, vibration and desktop notification when the noise exceeds a chosen decibel threshold. Exports measurements to CSV. Runs locally in the browser.',
        tags: ['audio', 'tool'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Towerwatch',
        href: './towerwatch/',
        glyph: '📡',
        tagline: 'Spot the rogue tower',
        description: 'Your phone trusts whichever mast shouts loudest. Towerwatch watches the mobile connection for the fingerprints of a fake one: sudden 2G downgrades, impossible signal strengths and cell IDs no public map has ever seen.',
        search: 'A rogue cell tower and fake base station detector that helps spot IMSI catchers and stingrays. Watches the mobile network connection live using the Network Information API for sudden 2G or GSM downgrades, dropped connections and slow network classes, and tracks your location with geolocation. Log or import cell tower data (MCC, MNC, LAC, TAC, cell ID, radio type, signal strength in dBm) from netmonitor apps such as NetMonster, Cellular-Z or CellMapper as CSV or JSON, and it scores each cell for suspicion using heuristics: reserved area codes, lone LAC or TAC, cloned cell identities, impossibly strong signals and cells seen kilometres apart. Optional OpenCelliD cross-check to see whether a cell is known to the public database, plus an exportable JSON report. Runs entirely in the browser, nothing uploaded.',
        tags: ['security', 'tool'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'PDF Search',
        href: './pdf-search/',
        glyph: '🔎',
        tagline: 'One search, every PDF',
        description: 'A shelf of PDFs with their full text extracted, searchable all at once. Pick which documents to look in, search words, phrases or exclusions, and jump straight to the page that mentions them.',
        search: 'A full text search engine for PDF documents that searches across several PDFs at the same time. Extracts the text of each PDF into a JavaScript index so you can search for keywords, subjects, titles, phrases and clues across a whole shelf of documents at once, select which documents to include, exclude words, match whole words only, see highlighted snippets in context and open the source PDF at the exact page. Currently holds the EU Cyber Resilience Act, Regulation (EU) 2024/2847, and the Commission guidance C(2026) 5252 on applying it. Runs entirely in the browser with nothing uploaded.',
        tags: ['tool', 'search', 'documents'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'LaTeX Doctor',
        href: './latex-doctor/',
        glyph: '🩺',
        tagline: 'Diagnose broken LaTeX',
        description: 'Paste your LaTeX source and get an instant diagnosis: unbalanced braces, broken environments, stray math mode and other common mistakes, explained line by line.',
        search: 'A LaTeX syntax checker, linter and troubleshooter that runs entirely in the browser. Paste .tex code and find unbalanced or unmatched braces, mismatched or unclosed begin and end environments, unclosed inline or display math mode ($, $$, \\[ \\], \\( \\)), missing documentclass or begin end document, unescaped special characters like &, # and underscore outside math mode, missing usepackage requirements for commands such as includegraphics or textcolor, and common command and environment typos. Comments, verbatim and lstlisting blocks are skipped, so they never raise false alarms. No server, nothing uploaded, everything checked locally with plain HTML CSS and JavaScript.',
        tags: ['tool', 'latex'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Subnet Calculator',
        href: './subnets/',
        glyph: '🧮',
        tagline: 'Network cartographer',
        description: 'Carve IP space into tidy subnets with an interactive calculator and a grand reference table.',
        search: 'An IP subnet calculator for IPv4 networks. Compute subnet masks, CIDR ranges, network and broadcast addresses and host counts, with a subnetting reference table.',
        tags: ['tool', 'network'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'DNS Sinkhole',
        href: './DNS-sinkhole/',
        glyph: '🕳️',
        tagline: 'The void gate',
        description: 'Curated blocklists with regex black- and white-listing to banish unwanted domains into the abyss.',
        search: 'A DNS blocklist manager for ad blocking and tracker blocking with regex allowlist and blocklist support. Pi-hole style domain blocking and sinkhole.',
        tags: ['tool', 'network'],
        aura: 'pink',
        status: 'live',
    },
    {
        title: 'Scoreboard',
        href: './scoreboard/',
        glyph: '🏆',
        tagline: 'Arena of champions',
        description: 'A live registration and leaderboard system with a gamemaster’s control room for events and tournaments.',
        search: 'A live event registration and leaderboard scoreboard application with an admin gamemaster control panel for tournaments, competitions and games.',
        tags: ['app', 'games'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Engraving Gallery',
        href: './Engraving/',
        glyph: '⚙️',
        tagline: 'The etching bench',
        description: 'A searchable gallery of laser-engraving designs, ready to preview and download as PNG or SVG.',
        search: 'A searchable gallery of laser engraving designs and templates, previewable and downloadable as PNG or SVG image files.',
        tags: ['gallery', 'laser'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Laser Works',
        href: './laser/',
        glyph: '🔦',
        tagline: 'Precision atelier',
        description: 'A full storefront for a laser-cutting workshop: hero, services and all, still finding its words (and its photographs).',
        search: 'A business website and storefront for a laser cutting and engraving workshop, with hero section and services. Work in progress company site.',
        tags: ['site', 'laser'],
        aura: 'cyan',
        status: 'soon',
    },
    {
        title: 'Laser Forge',
        href: './laser-forge/',
        glyph: '📐',
        tagline: 'Design → machine files',
        description: 'Turn text, images, emoji and QR codes into machine-ready laser files, exportable as DXF, SVG and more.',
        search: 'A laser engraver and laser cutter design tool that generates machine ready files like DXF and SVG from text, images, emoji and QR codes.',
        tags: ['tool', 'laser'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Laser Forge · Direct Control',
        href: './laser-forge-v2/',
        glyph: '🎛️',
        tagline: 'Driving the laser live, soon',
        description: 'The next Laser Forge: everything v1 can do, plus multi-select, boolean shapes and the headline spell: Web Serial control to drive a connected engraver straight from the browser. Still on the workbench.',
        search: 'A work in progress enhanced laser engraver design tool that will add Web Serial direct machine control: connect to a GRBL laser engraver or cutter over USB serial from the browser, jog the head, home, set origin, frame the job and stream G-code, plus multi-select, boolean operations and SVG and DXF import. Not finished yet.',
        tags: ['tool', 'laser'],
        aura: 'cyan',
        status: 'soon',
    },
    {
        title: 'Window View',
        href: './dashboard_v1/',
        glyph: '🪟',
        tagline: 'A shelf with a view',
        description: 'A decorative shelf-and-bracket dashboard component, an early cut of a personal cockpit, not yet a dashboard.',
        search: 'An early dashboard user interface component: a decorative shelf and bracket widget, a prototype of a personal dashboard cockpit and homepage.',
        tags: ['ui', 'wip'],
        aura: 'violet',
        status: 'soon',
    },
    {
        title: 'IT News Scroll',
        href: './news/',
        glyph: '📰',
        tagline: 'The daily scroll',
        description: 'A curated shelf of IT and security reading, labs, CTFs, OSINT and lookup tools, next to the European conference and hacker camp calendar seen from Belgium. Filter it, search it, share the link.',
        search: 'A curated directory of IT and cybersecurity learning resources, news sources, blogs, podcasts, YouTube channels, newsletters, communities, hands-on labs, CTF platforms, OSINT tools, incident response and threat intelligence lookups, security frameworks such as MITRE ATT&CK, OWASP Top 10, NIST CSF, CIS Controls, the CISA KEV catalog and the Belgian CyberFundamentals framework, plus Belgian and European sources including the Centre for Cybersecurity Belgium, CERT.be, Safeonweb, the Cyber Security Coalition and ENISA. Also a calendar of hacker conferences, security conferences, hacker camps, CTF competitions, trade fairs, trainings and meetups in Belgium and across Europe: BruCON, Fri3d Camp, FOSDEM, Cybersec Europe, BE-CYBER, Devoxx Belgium, Techorama, BSides Limburg, Cyber Security Challenge Belgium, SecAppDev, the Dutch four yearly hacker camp WHY MCH SHA OHM, Hardwear.io, ONE Conference, BSides Amsterdam, hack.lu in Luxembourg, Pass the SALT and leHACK and SSTIC and Botconf and Barbhack in France, the Chaos Communication Congress and Chaos Communication Camp and GPN and MRMCD and TROOPERS and OffensiveCon and FrOSCon in Germany, EMF Camp and 44CON and BSides London and SteelCon and CYBERUK in the United Kingdom, BornHack in Denmark, SEC-T and Security Fest in Sweden, Disobey in Finland, Insomni hack and Black Alps and Area41 in Switzerland, DeepSec in Austria, RomHack and No Hat and HackInBo in Italy, RootedCON in Spain, BSides Lisbon in Portugal, CONFidence and x33fcon in Poland, Hacktivity in Hungary, DefCamp in Romania and the European Cyber Security Challenge. Also Hexacon and GreHack and Sthack and Devoxx France and Paris Web in France, Hackerhotel and WICCON and NLUUG and the Dutch PHP Conference in the Netherlands, EuroBSDCon and Fri3d Camp and Nerdland in Belgium, Luxembourg Internet Days, it-sa and secIT and BSides Munich and BSides Berlin and Hackover and JavaLand in Germany, Black Hat Europe and Infosecurity Europe and the whole BSides circuit in the United Kingdom, and online events such as Advent of Code, the Flare-On challenge, the SANS Holiday Hack Challenge, Google CTF, NahamCon, Microsoft Ignite and Build and the RIPE meetings. OSINT tools include Shodan, Censys, Netlas, ONYPHE, ZoomEye, FOFA, LeakIX, SecurityTrails, crt.sh, urlscan, WhatsMyName, Epieos, Intelligence X, Have I Been Pwned, WiGLE, OpenCorporates, the Belgian company register KBO BCE, OpenSanctions, OCCRP Aleph, reverse image search, image forensics, chronolocation with SunCalc, Overpass Turbo, flight and vessel tracking, and BGP and RIPE lookups. Answers the question where can I learn IT security, what security conference should I go to, and which hacker events are near Belgium.',
        tags: ['app', 'learning', 'events'],
        aura: 'pink',
        status: 'live',
    },
    {
        title: 'Disk Filler',
        href: './fill/',
        glyph: '🗄️',
        tagline: 'A harmless storage prank',
        description: 'A gentle troll that stuffs the browser’s localStorage with cat pictures, fully reversible with a single click.',
        search: 'A harmless prank tool that fills up the browser localStorage and disk space with cat images as a joke, fully reversible with a stop button to clear it.',
        tags: ['prank', 'fun'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Document Censor',
        href: './blur/',
        glyph: '🫥',
        tagline: 'Hide the secrets',
        description: 'Mask sensitive text and pixels before you share a screenshot with the world.',
        search: 'A tool to redact, censor and blur sensitive text and pixels in images and screenshots before sharing. Hide private or confidential information.',
        tags: ['tool', 'privacy'],
        aura: 'violet',
        status: 'live',
    },
    {
        title: 'Privacy Broom',
        href: './clear/',
        glyph: '🧹',
        tagline: 'Sweep your traces',
        description: 'A one-click sweep for browser caches and lingering traces.',
        search: 'A one-click tool to clear the browser cache, cookies and lingering browsing traces for privacy and cleanup.',
        tags: ['tool', 'privacy'],
        aura: 'cyan',
        status: 'live',
    },
    {
        title: 'Wishlist Scroll',
        href: './to-check/',
        glyph: '🔖',
        tagline: 'Tools to explore',
        description: 'A searchable table of intriguing GitHub tools waiting to be tried and tested.',
        search: 'A searchable table of interesting GitHub tools and open source projects to try and evaluate later. A software bookmarks and wishlist list.',
        tags: ['links', 'reference'],
        aura: 'gold',
        status: 'live',
    },
    {
        title: 'Tinkerer’s Desk',
        href: './rami/',
        glyph: '🧑‍🔬',
        tagline: 'A scratch page',
        description: 'A personal scratch page with handy little utilities and links: a workbench, not an exhibit.',
        search: 'A personal scratch and sandbox page with small utilities, handy links and experiments.',
        tags: ['personal', 'wip'],
        aura: 'violet',
        status: 'soon',
    },
];

/* ==========================================================================
   Planned projects, the hidden fourth realm.
   Names of spells not yet begun. Shown as a chip-list under the Workshop.
   Move a name up into RAMI_WORKSHOP once its folder exists and has content.
   ========================================================================== */
window.RAMI_PLANNED = [
    { name: 'Screen Fill', note: 'Fill the screen with solid colours to hunt dead pixels.' },
    { name: 'Boolean Bench', note: 'Union, subtract and intersect shapes, the missing spell in both Forges.' },
    { name: 'Sitemap Scribe', note: 'Generate sitemap.xml straight from this very registry.' },
    { name: 'Realm Sentinel', note: 'A link-and-asset checker that walks every realm and reports the rot.' },
    { name: 'Colour Grimoire', note: 'Palette conjurer with contrast checking and export to CSS tokens.' },
];

/* ==========================================================================
   The Workshop cards are rendered straight from RAMI_WORKSHOP onto the hub,
   so there is no portal card to keep in sync any more.
   ========================================================================== */
