/* ==========================================================================
   Keyshift — physical keyboard layout tables
   --------------------------------------------------------------------------
   Every layout maps an ISO key position to the characters it produces:

       KEYID: [ unshifted, shifted, AltGr, AltGr+Shift ]

   Key ids follow the X11/XKB convention, so AD01 is always the physical key
   in the top letter row on the far left — labelled Q on QWERTY, A on AZERTY.
   That position, not the letter printed on it, is what a remote machine
   actually receives.

   A layout without an LSGT entry has no key between Left Shift and the Z/W
   position, which is the case on 104-key ANSI boards. That single missing
   key is why a backslash is unreachable on a Belgian remote session from a
   US keyboard.
   ========================================================================== */

window.KEYSHIFT_ROWS = [
    ['TLDE', 'AE01', 'AE02', 'AE03', 'AE04', 'AE05', 'AE06', 'AE07', 'AE08', 'AE09', 'AE10', 'AE11', 'AE12'],
    ['AD01', 'AD02', 'AD03', 'AD04', 'AD05', 'AD06', 'AD07', 'AD08', 'AD09', 'AD10', 'AD11', 'AD12'],
    ['AC01', 'AC02', 'AC03', 'AC04', 'AC05', 'AC06', 'AC07', 'AC08', 'AC09', 'AC10', 'AC11', 'BKSL'],
    ['LSGT', 'AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB08', 'AB09', 'AB10']
];

/* Leading indent per row, in key-widths, so the diagram staggers like a real board. */
window.KEYSHIFT_ROW_OFFSET = [0, 0.5, 0.75, 0];

window.KEYSHIFT_MODS = ['', 'Shift', 'AltGr', 'AltGr + Shift'];

window.KEYSHIFT_LAYOUTS = [
    {
        id: 'us-intl',
        name: 'QWERTY US International',
        short: 'US-Intl',
        note: 'The US layout with dead keys. Apostrophe, quote, backtick, tilde and caret wait for the next key instead of printing straight away.',
        dead: ['\'', '"', '`', '~', '^'],
        keys: {
            TLDE: ['`', '~'],
            AE01: ['1', '!', '\u00a1', '\u00b9'],
            AE02: ['2', '@', '\u00b2'],
            AE03: ['3', '#', '\u00b3'],
            AE04: ['4', '$', '\u00a4', '\u00a3'],
            AE05: ['5', '%', '\u20ac'],
            AE06: ['6', '^', '\u00bc'],
            AE07: ['7', '&', '\u00bd'],
            AE08: ['8', '*', '\u00be'],
            AE09: ['9', '(', '\u2018'],
            AE10: ['0', ')', '\u2019'],
            AE11: ['-', '_', '\u00a5'],
            AE12: ['=', '+', '\u00d7', '\u00f7'],
            AD01: ['q', 'Q', '\u00e4', '\u00c4'],
            AD02: ['w', 'W', '\u00e5', '\u00c5'],
            AD03: ['e', 'E', '\u00e9', '\u00c9'],
            AD04: ['r', 'R', '\u00ae'],
            AD05: ['t', 'T', '\u00fe', '\u00de'],
            AD06: ['y', 'Y', '\u00fc', '\u00dc'],
            AD07: ['u', 'U', '\u00fa', '\u00da'],
            AD08: ['i', 'I', '\u00ed', '\u00cd'],
            AD09: ['o', 'O', '\u00f3', '\u00d3'],
            AD10: ['p', 'P', '\u00f6', '\u00d6'],
            AD11: ['[', '{', '\u00ab'],
            AD12: [']', '}', '\u00bb'],
            AC01: ['a', 'A', '\u00e1', '\u00c1'],
            AC02: ['s', 'S', '\u00df', '\u00a7'],
            AC03: ['d', 'D', '\u00f0', '\u00d0'],
            AC04: ['f', 'F'],
            AC05: ['g', 'G'],
            AC06: ['h', 'H'],
            AC07: ['j', 'J'],
            AC08: ['k', 'K'],
            AC09: ['l', 'L', '\u00f8', '\u00d8'],
            AC10: [';', ':', '\u00b6', '\u00b0'],
            AC11: ['\'', '"', '\u00b4', '\u00a8'],
            BKSL: ['\\', '|', '\u00ac', '\u00a6'],
            AB01: ['z', 'Z', '\u00e6', '\u00c6'],
            AB02: ['x', 'X'],
            AB03: ['c', 'C', '\u00a9', '\u00a2'],
            AB04: ['v', 'V'],
            AB05: ['b', 'B'],
            AB06: ['n', 'N', '\u00f1', '\u00d1'],
            AB07: ['m', 'M', '\u00b5'],
            AB08: [',', '<', '\u00e7', '\u00c7'],
            AB09: ['.', '>'],
            AB10: ['/', '?', '\u00bf'],
            SPCE: [' ']
        }
    },
    {
        id: 'us',
        name: 'QWERTY US (plain)',
        short: 'US',
        note: 'The plain US layout. No dead keys and no AltGr layer, so quotes and accents behave literally.',
        dead: [],
        keys: {
            TLDE: ['`', '~'],
            AE01: ['1', '!'],
            AE02: ['2', '@'],
            AE03: ['3', '#'],
            AE04: ['4', '$'],
            AE05: ['5', '%'],
            AE06: ['6', '^'],
            AE07: ['7', '&'],
            AE08: ['8', '*'],
            AE09: ['9', '('],
            AE10: ['0', ')'],
            AE11: ['-', '_'],
            AE12: ['=', '+'],
            AD01: ['q', 'Q'],
            AD02: ['w', 'W'],
            AD03: ['e', 'E'],
            AD04: ['r', 'R'],
            AD05: ['t', 'T'],
            AD06: ['y', 'Y'],
            AD07: ['u', 'U'],
            AD08: ['i', 'I'],
            AD09: ['o', 'O'],
            AD10: ['p', 'P'],
            AD11: ['[', '{'],
            AD12: [']', '}'],
            AC01: ['a', 'A'],
            AC02: ['s', 'S'],
            AC03: ['d', 'D'],
            AC04: ['f', 'F'],
            AC05: ['g', 'G'],
            AC06: ['h', 'H'],
            AC07: ['j', 'J'],
            AC08: ['k', 'K'],
            AC09: ['l', 'L'],
            AC10: [';', ':'],
            AC11: ['\'', '"'],
            BKSL: ['\\', '|'],
            AB01: ['z', 'Z'],
            AB02: ['x', 'X'],
            AB03: ['c', 'C'],
            AB04: ['v', 'V'],
            AB05: ['b', 'B'],
            AB06: ['n', 'N'],
            AB07: ['m', 'M'],
            AB08: [',', '<'],
            AB09: ['.', '>'],
            AB10: ['/', '?'],
            SPCE: [' ']
        }
    },
    {
        id: 'be',
        name: 'AZERTY Belgian (period)',
        short: 'BE',
        note: 'The standard Belgian layout. Digits need Shift, and @ # [ ] { } | \\ ~ all sit on the AltGr layer.',
        dead: ['^', '\u00a8', '`', '\u00b4', '~'],
        keys: {
            TLDE: ['\u00b2', '\u00b3'],
            AE01: ['&', '1', '|'],
            AE02: ['\u00e9', '2', '@'],
            AE03: ['"', '3', '#'],
            AE04: ['\'', '4'],
            AE05: ['(', '5'],
            AE06: ['\u00a7', '6', '^'],
            AE07: ['\u00e8', '7'],
            AE08: ['!', '8'],
            AE09: ['\u00e7', '9', '{'],
            AE10: ['\u00e0', '0', '}'],
            AE11: [')', '\u00b0'],
            AE12: ['-', '_'],
            AD01: ['a', 'A'],
            AD02: ['z', 'Z'],
            AD03: ['e', 'E', '\u20ac'],
            AD04: ['r', 'R'],
            AD05: ['t', 'T'],
            AD06: ['y', 'Y'],
            AD07: ['u', 'U'],
            AD08: ['i', 'I'],
            AD09: ['o', 'O'],
            AD10: ['p', 'P'],
            AD11: ['^', '\u00a8', '['],
            AD12: ['$', '*', ']'],
            AC01: ['q', 'Q'],
            AC02: ['s', 'S'],
            AC03: ['d', 'D'],
            AC04: ['f', 'F'],
            AC05: ['g', 'G'],
            AC06: ['h', 'H'],
            AC07: ['j', 'J'],
            AC08: ['k', 'K'],
            AC09: ['l', 'L'],
            AC10: ['m', 'M'],
            AC11: ['\u00f9', '%', '\u00b4'],
            BKSL: ['\u00b5', '\u00a3', '`'],
            LSGT: ['<', '>', '\\'],
            AB01: ['w', 'W'],
            AB02: ['x', 'X'],
            AB03: ['c', 'C'],
            AB04: ['v', 'V'],
            AB05: ['b', 'B'],
            AB06: ['n', 'N'],
            AB07: [',', '?'],
            AB08: [';', '.'],
            AB09: [':', '/'],
            AB10: ['=', '+', '~'],
            SPCE: [' ']
        }
    },
    {
        id: 'fr',
        name: 'AZERTY French',
        short: 'FR',
        note: 'Close to Belgian but not the same. The whole punctuation row is shuffled, so a Belgian mapping will still come out wrong here.',
        dead: ['^', '\u00a8', '`', '~'],
        keys: {
            TLDE: ['\u00b2'],
            AE01: ['&', '1'],
            AE02: ['\u00e9', '2', '~'],
            AE03: ['"', '3', '#'],
            AE04: ['\'', '4', '{'],
            AE05: ['(', '5', '['],
            AE06: ['-', '6', '|'],
            AE07: ['\u00e8', '7', '`'],
            AE08: ['_', '8', '\\'],
            AE09: ['\u00e7', '9', '^'],
            AE10: ['\u00e0', '0', '@'],
            AE11: [')', '\u00b0', ']'],
            AE12: ['=', '+', '}'],
            AD01: ['a', 'A'],
            AD02: ['z', 'Z'],
            AD03: ['e', 'E', '\u20ac'],
            AD04: ['r', 'R'],
            AD05: ['t', 'T'],
            AD06: ['y', 'Y'],
            AD07: ['u', 'U'],
            AD08: ['i', 'I'],
            AD09: ['o', 'O'],
            AD10: ['p', 'P'],
            AD11: ['^', '\u00a8'],
            AD12: ['$', '\u00a3', '\u00a4'],
            AC01: ['q', 'Q'],
            AC02: ['s', 'S'],
            AC03: ['d', 'D'],
            AC04: ['f', 'F'],
            AC05: ['g', 'G'],
            AC06: ['h', 'H'],
            AC07: ['j', 'J'],
            AC08: ['k', 'K'],
            AC09: ['l', 'L'],
            AC10: ['m', 'M'],
            AC11: ['\u00f9', '%'],
            BKSL: ['*', '\u00b5'],
            LSGT: ['<', '>'],
            AB01: ['w', 'W'],
            AB02: ['x', 'X'],
            AB03: ['c', 'C'],
            AB04: ['v', 'V'],
            AB05: ['b', 'B'],
            AB06: ['n', 'N'],
            AB07: [',', '?'],
            AB08: [';', '.'],
            AB09: [':', '/'],
            AB10: ['!', '\u00a7'],
            SPCE: [' ']
        }
    }
];
