/* ==========================================================================
   Breachlight — data-terms.js
   --------------------------------------------------------------------------
   The vocabulary. Written for someone who has just been told a word by their
   bank, their IT department or a news article and has no idea what it means.

   Schema
     id      stable — hash links point at it, never rename
     term    the headword
     also    other names for the same thing (searched, shown as "also called")
     say     pronunciation, only where the word is genuinely misleading
     glyph   one character
     cat     social | delivery | money | technical | defence | pro
     aud     'both' | 'user' | 'pro'   (which mode surfaces it first)
     what    the plain definition — one or two sentences, no jargon
     spot    how to recognise it in the wild
     eg      a concrete, believable example
     keys    search keywords, INCLUDING the words a scared person actually types
   ========================================================================== */

window.BL_CATS = [
    { id: 'social', title: 'Social engineering', glyph: '🎭', blurb: 'Attacks on people, not computers. The oldest and still the best.' },
    { id: 'delivery', title: 'How it reaches you', glyph: '📬', blurb: 'Email, SMS, phone, QR, ads, search results — the delivery vans of fraud.' },
    { id: 'money', title: 'Money and fraud', glyph: '💸', blurb: 'The part where you are actually poorer.' },
    { id: 'technical', title: 'Technical attacks', glyph: '⚙️', blurb: 'Malware, sessions, tokens and the machinery behind the con.' },
    { id: 'defence', title: 'Defensive words', glyph: '🛡', blurb: 'The things that protect you, and what the names mean.' },
    { id: 'pro', title: 'Responder jargon', glyph: '📡', blurb: 'What the incident response team says to each other.' },
];

window.BL_TERMS = [

    /* ============================================================== SOCIAL == */
    {
        id: 'social-engineering',
        term: 'Social engineering',
        also: ['human hacking', 'con'],
        glyph: '🎭',
        cat: 'social',
        aud: 'both',
        what: 'Getting a person to do something against their own interest by manipulating them, rather than by breaking any technology. It is the parent category: phishing, vishing, pretexting and most fraud are just social engineering with different delivery vans.',
        spot: [
            '**Urgency.** A deadline that exists only in the message. "Within 24 hours or your account is closed."',
            '**Authority.** Someone senior, official or armed with a title — the CEO, the tax office, the police, the fraud department.',
            '**Fear or greed.** A threat you want to make go away, or a reward you want to grab.',
            '**Isolation.** "Do not discuss this with anyone." "Do not tell the bank staff, this is a secret investigation." A real organisation never asks that.',
            '**A channel change.** Contact starts on a platform with protections and moves to WhatsApp, Telegram or SMS where there are none.',
        ],
        eg: 'A caller says he is from your bank’s fraud team, already knows your name and the last four digits of your card, and needs the code you are about to receive "to cancel the fraudulent payment". The code is authorising the payment.',
        keys: 'social engineering human hacking manipulation con artist psychology tricked fooled manipulated scam scammed conned pressure urgency authority',
    },
    {
        id: 'pretexting',
        term: 'Pretexting',
        glyph: '🎬',
        cat: 'social',
        aud: 'both',
        what: 'Inventing a believable story and a role to justify the request. The attacker does not just ask for the thing, they build a small piece of theatre so that asking is the natural next step.',
        spot: [
            'A story that explains, in advance, why you cannot verify it the normal way. "I am calling from my personal phone because the office system is down."',
            'Details that are true and public — your manager’s name, your office address, a real project — used as proof of legitimacy. They are not proof of anything.',
            'The request always arrives after the story, never before.',
        ],
        eg: '"Hi, it’s Marc from the audit firm. We are finalising the year end and your finance manager asked me to reconcile a supplier list with you. Can you confirm the bank details we have on file?"',
        keys: 'pretexting pretext fake story impersonation cover story roleplay lie invented scenario',
    },
    {
        id: 'baiting',
        term: 'Baiting',
        glyph: '🪤',
        cat: 'social',
        aud: 'both',
        what: 'Leaving something tempting where a curious person will pick it up. Classically a USB stick in a car park, now more often a free download, a cracked game, a pirated film or a "leaked salary spreadsheet".',
        spot: [
            'Something valuable that nobody is charging for, and no obvious reason why.',
            'A file that has to be run rather than viewed.',
            'Found media — a USB stick, an SD card, a QR sticker — with a label designed to make you curious.',
        ],
        eg: 'A USB stick labelled "Redundancies 2026 — CONFIDENTIAL" left on a canteen table. Plugging it in installs a remote access tool before the spreadsheet even opens.',
        keys: 'baiting bait usb stick found drive free download cracked pirated curiosity trap',
    },
    {
        id: 'quid-pro-quo',
        term: 'Quid pro quo',
        also: ['something for something'],
        glyph: '🤝',
        cat: 'social',
        aud: 'both',
        what: 'The attacker offers a service in exchange for access. It feels like a fair trade, which is why it works better than a naked demand.',
        spot: [
            'Unsolicited help. Nobody from IT rings you out of the blue to fix a problem you did not report.',
            'A small favour requested "while I am in here anyway" — install this, disable that, read me the code.',
        ],
        eg: '"IT helpdesk here, we are patching a laptop fault across the floor. I can fix yours now if you install this remote support tool."',
        keys: 'quid pro quo something for something free help fake it support helpdesk trade favour',
    },
    {
        id: 'tailgating',
        term: 'Tailgating',
        also: ['piggybacking'],
        glyph: '🚪',
        cat: 'social',
        aud: 'both',
        what: 'Walking into a secure building behind someone who legitimately badged in. Politeness is the exploit — most people will not let a door close on a stranger carrying boxes.',
        spot: [
            'Full hands, no badge, apologetic smile. Coffee trays and cardboard boxes are professional tools.',
            'High-visibility clothing and a clipboard. A uniform is the cheapest credential there is.',
        ],
        eg: 'Someone in a delivery jacket balances two parcels and asks you to hold the turnstile. They are inside the building and past every firewall you own.',
        keys: 'tailgating piggybacking door badge building physical access follow me in stranger office',
    },
    {
        id: 'shoulder-surfing',
        term: 'Shoulder surfing',
        glyph: '👀',
        cat: 'social',
        aud: 'user',
        what: 'Reading your screen, keyboard or PIN pad over your shoulder — on a train, in a queue, in an open-plan office, or through a café window.',
        spot: [
            'Someone with a clear line of sight to your screen at a cash machine, a till or a train seat.',
            'Phone cameras held at an angle that makes no sense for a selfie.',
        ],
        eg: 'A PIN entered at a supermarket till, seen once, is enough — the card only has to be lifted afterwards.',
        keys: 'shoulder surfing watching my screen pin stolen looking over shoulder train cafe overlooked privacy screen',
    },
    {
        id: 'dumpster-diving',
        term: 'Dumpster diving',
        also: ['bin raiding'],
        glyph: '🗑',
        cat: 'social',
        aud: 'both',
        what: 'Going through rubbish for the raw material of fraud: bank statements, invoices, org charts, old hard drives, sticky notes.',
        spot: ['Anything with your name, account number or an internal system name on it that leaves the building intact.'],
        eg: 'A discarded invoice gives an attacker your supplier’s name, your reference number and your finance contact — enough to write a very convincing invoice-fraud email.',
        keys: 'dumpster diving bin rubbish trash shredding documents thrown away paperwork statements',
    },
    {
        id: 'impersonation',
        term: 'Impersonation',
        glyph: '🪞',
        cat: 'social',
        aud: 'both',
        what: 'Pretending to be a specific person or organisation you already trust: your bank, your boss, your child, a courier, the tax office, the police.',
        spot: [
            'The identity is asserted, never proved. Anyone can type a name into a From field.',
            'Verification is discouraged, deflected or made to feel rude.',
        ],
        eg: 'A WhatsApp message from an unknown number: "Hi Mum, dropped my phone in the sink, this is my new number. Can you pay a bill for me?"',
        keys: 'impersonation impersonating pretending to be my boss my bank my son my daughter hi mum hi dad new number fake identity',
    },

    /* ============================================================ DELIVERY == */
    {
        id: 'phishing',
        term: 'Phishing',
        say: 'FISH-ing',
        glyph: '🎣',
        cat: 'delivery',
        aud: 'both',
        what: 'A message pretending to be from someone you trust, designed to make you hand over a password, a code or money, or to run a file. Classically email, but the word is now used for the whole family.',
        spot: [
            'A link that wants you to log in, sent to you rather than found by you.',
            'The display name is right but the actual address is not. Expand it and read the part after the last @.',
            'A generic greeting, or an oddly specific one that came from your own social media.',
            'The message is the only place the deadline exists.',
            'It works on your emotions before it works on your mouse: panic, curiosity, a refund, a parcel, a fine.',
        ],
        eg: 'An email styled exactly like your bank saying an unrecognised device signed in, with a big **Secure my account** button that goes to `bank-verify-eu.help`.',
        keys: 'phishing phish phishing email fake email scam email i got phished think i was phished suspicious email fraudulent email fake bank email',
    },
    {
        id: 'spear-phishing',
        term: 'Spear phishing',
        glyph: '🏹',
        cat: 'delivery',
        aud: 'both',
        what: 'Phishing aimed at one named person, written using real details about them. Far fewer messages, far higher success rate, and none of the usual clumsy spelling.',
        spot: [
            'It knows things: your project, your manager, your last conference, your supplier’s name.',
            'It is grammatically fine. "Bad English" has not been a reliable signal for years.',
            'It arrives at a plausible moment — the week of an invoice run, the day after a public announcement.',
        ],
        eg: 'A message to the finance officer referencing the real contract number and the real supplier, asking to update the payment details "before Friday’s run".',
        keys: 'spear phishing targeted phishing personalised knows my name specific attack researched me',
    },
    {
        id: 'whaling',
        term: 'Whaling',
        also: ['CEO fraud (inbound)'],
        glyph: '🐋',
        cat: 'delivery',
        aud: 'both',
        what: 'Spear phishing aimed at the big fish — directors, CFOs, founders. The payoff is bigger and the target is usually the one person who can override every control.',
        spot: [
            'Board-level bait: an acquisition document, a legal notice, a shareholder query.',
            'Requests that lean on the target’s authority to bypass process.',
        ],
        eg: 'A "confidential due diligence portal" invitation sent to a CFO the week a merger is rumoured.',
        keys: 'whaling ceo cfo director executive board targeted senior management big fish',
    },
    {
        id: 'clone-phishing',
        term: 'Clone phishing',
        glyph: '👯',
        cat: 'delivery',
        aud: 'both',
        what: 'A copy of a real email you already received, resent with the link or attachment swapped for a malicious one — usually with "Resending, the last link was broken."',
        spot: [
            'You genuinely have received this email before. That is the point.',
            'The apology for resending is doing all the work.',
        ],
        eg: 'A duplicate of last week’s genuine payslip notification, "corrected", pointing at a lookalike login page.',
        keys: 'clone phishing duplicate email resent resending copy of real email same email twice',
    },
    {
        id: 'smishing',
        term: 'Smishing',
        say: 'SMISH-ing — SMS + phishing',
        also: ['SMS phishing', 'text message scam'],
        glyph: '💬',
        cat: 'delivery',
        aud: 'both',
        what: 'Phishing by text message, WhatsApp, iMessage or RCS. Short, urgent, and stripped of the clues you would use in email — no letterhead, no signature, and a shortened link.',
        spot: [
            'Parcels, customs fees, unpaid tolls, tax refunds, "your account is suspended", "is this you?".',
            'A shortened or unfamiliar link. Legitimate banks do not send login links by SMS.',
            'It lands in the same thread as real messages from that brand — SMS sender IDs are trivially spoofed, so the thread proves nothing.',
        ],
        eg: '"Your parcel is held at customs. Pay €2.99 to release: bpost-fees.co" — the €2.99 is only there to collect the card number.',
        keys: 'smishing sms phishing text message scam whatsapp scam fake sms parcel text customs fee text i clicked a text link',
    },
    {
        id: 'vishing',
        term: 'Vishing',
        say: 'VISH-ing — voice + phishing',
        also: ['voice phishing', 'phone scam'],
        glyph: '📞',
        cat: 'delivery',
        aud: 'both',
        what: 'Phishing by phone call. A live human is far more persuasive than an email, can adapt to your objections, and can keep you on the line while the fraud completes.',
        spot: [
            'They called you. That is the single most important fact in the conversation.',
            'They ask for a code, a password, a remote session, or for you to "move your money to a safe account". No bank, police force or tax office ever does any of those.',
            'Caller ID shows the real number of your bank. Caller ID can be forged and is worth nothing.',
            'They discourage you from hanging up and calling back — because the line may stay open on old landlines, and because the spell breaks.',
        ],
        eg: '"This is the fraud department. We have blocked two payments. To reverse them I need the six-digit code we have just sent you." The code approves a new payment.',
        keys: 'vishing voice phishing phone call scam fake bank call cold call they called me safe account fraud department microsoft called',
    },
    {
        id: 'quishing',
        term: 'Quishing',
        say: 'KWISH-ing — QR + phishing',
        also: ['QR phishing', 'QR code scam'],
        glyph: '🔳',
        cat: 'delivery',
        aud: 'both',
        what: 'A malicious QR code. You cannot read a QR code with your eyes, so it moves the decision from "does this link look right?" to "do I trust this piece of printed paper?" It also jumps you from a monitored work computer to an unmonitored personal phone.',
        spot: [
            'A sticker stuck over an existing code — on a parking meter, an EV charger, a restaurant table, a poster.',
            'A QR code inside an email or a PDF. There is no good reason to put a QR code in a message that arrived on a screen.',
            'A code that leads to a login page or a payment page rather than information.',
            'Always read the URL your camera previews **before** tapping it, and check the domain, not the words around it.',
        ],
        eg: 'A "renew your multi-factor authentication" email containing only a QR code, so the company’s email link scanner has nothing to inspect.',
        keys: 'quishing qr code scam scanned a qr code malicious qr sticker parking meter qr fake qr i scanned a code',
    },
    {
        id: 'angler-phishing',
        term: 'Angler phishing',
        glyph: '🪝',
        cat: 'delivery',
        aud: 'user',
        what: 'Fake customer support accounts on social media that pounce when you publicly complain to a brand.',
        spot: [
            'They reply within minutes of your complaint, from a handle with an extra underscore or a zero for an o.',
            'They move you to DM, then to WhatsApp, then ask you to "verify" your account.',
        ],
        eg: 'You tweet at an airline about a delayed refund; "@airline_help_desk" DMs you a link to "confirm your booking and card".',
        keys: 'angler phishing fake support account social media twitter x instagram dm fake customer service replied to my complaint',
    },
    {
        id: 'malvertising',
        term: 'Malvertising',
        glyph: '📢',
        cat: 'delivery',
        aud: 'both',
        what: 'Buying ordinary online advertising to deliver malware or a fake download page. The ad network is legitimate; the advertiser is not.',
        spot: [
            'The sponsored result at the top of a search is not the official site. Scroll past the ads.',
            'Downloads of popular free software (browsers, PDF tools, remote support, crypto wallets) are the favourite bait.',
        ],
        eg: 'Searching for a well-known screen-recording tool, clicking the first sponsored result, and installing a signed-looking installer that also drops an infostealer.',
        keys: 'malvertising malicious ads sponsored result fake download search ads google ad fake installer',
    },
    {
        id: 'seo-poisoning',
        term: 'SEO poisoning',
        glyph: '🔍',
        cat: 'delivery',
        aud: 'both',
        what: 'Pushing a malicious page into the top organic search results for a phrase people search when they are already in trouble — "printer driver", "how to cancel subscription", "helpline number".',
        spot: [
            'A support phone number found via a search engine rather than on the back of your card or the product itself.',
            'Sites full of plausible, slightly-off text with one prominent download or phone number.',
        ],
        eg: 'A top result for "PayPal customer service phone number" that is a call centre run by fraudsters.',
        keys: 'seo poisoning fake search result helpline number found online fake support number search engine malware',
    },
    {
        id: 'watering-hole',
        term: 'Watering hole attack',
        glyph: '🕳',
        cat: 'delivery',
        aud: 'pro',
        what: 'Compromising a legitimate site the intended victims already visit — an industry forum, a supplier’s portal, a local news site — and letting them come to it.',
        spot: ['Infections clustered by profession or sector rather than by who received an email.'],
        eg: 'A regional trade association website is compromised and serves a fake browser update to visitors from a handful of target companies.',
        keys: 'watering hole compromised website supply chain visitors targeted sector drive by',
    },
    {
        id: 'pharming',
        term: 'Pharming',
        glyph: '🧭',
        cat: 'delivery',
        aud: 'both',
        what: 'Sending you to a fake site even though you typed the correct address, by poisoning DNS or tampering with your router or hosts file. There is no bad link to spot.',
        spot: [
            'Certificate warnings you have never seen before on a site you use daily.',
            'A router whose DNS servers you did not set, or whose admin password is still the default.',
        ],
        eg: 'A home router with a default password has its DNS changed; typing your bank’s real address lands on a perfect copy.',
        keys: 'pharming dns hijack router hacked hosts file redirected wrong site typed correct address certificate warning',
    },
    {
        id: 'typosquatting',
        term: 'Typosquatting',
        also: ['URL hijacking'],
        glyph: '⌨️',
        cat: 'delivery',
        aud: 'both',
        what: 'Registering domains that are one slip away from a real one — a missing letter, a doubled letter, `.co` instead of `.com` — and waiting for the traffic.',
        spot: ['Read the domain right to left from the last dot before the first slash. That is the only part that decides where you are.'],
        eg: '`gmial.com`, `paypa1.com`, `micros0ft-support.com`, `amaz0n.co`.',
        keys: 'typosquatting typo domain misspelled url lookalike domain wrong address fake website address',
    },
    {
        id: 'homograph',
        term: 'Homograph attack',
        also: ['IDN spoofing', 'punycode attack'],
        glyph: '🔤',
        cat: 'delivery',
        aud: 'both',
        what: 'Using letters from other alphabets that look identical to Latin ones — a Cyrillic "а" in place of an "a" — so the address is visually perfect but technically a completely different domain.',
        spot: [
            'You cannot spot this by looking. Browsers usually reveal it as `xn--` gibberish in the address bar; if you see `xn--`, leave.',
            'This is why a bookmark or a typed address beats a link every single time.',
        ],
        eg: '`аpple.com` where the first character is Cyrillic — renders identically, resolves to `xn--pple-43d.com`.',
        keys: 'homograph punycode idn unicode domain lookalike identical letters cyrillic xn-- fake url',
    },
    {
        id: 'open-redirect',
        term: 'Open redirect',
        glyph: '↪️',
        cat: 'delivery',
        aud: 'both',
        what: 'A genuine, trusted site that will bounce a visitor onwards to any address given in the link. The visible domain is real, so link filters and cautious humans both wave it through.',
        spot: ['A long link containing a second address after `?url=`, `?redirect=`, `?next=` or `?target=`. Read to the end, not just the start.'],
        eg: '`https://trusted-brand.com/out?url=https://login-verify.click` — the first half is real and irrelevant.',
        keys: 'open redirect link looks legitimate redirect url parameter trusted domain but fake redirected me',
    },
    {
        id: 'callback-phishing',
        term: 'Callback phishing',
        also: ['TOAD', 'telephone-oriented attack delivery'],
        glyph: '☎️',
        cat: 'delivery',
        aud: 'both',
        what: 'An email with no link and no attachment — just an invoice for something you did not buy and a phone number to dispute it. Nothing for a scanner to catch, and you make the first move, which makes you trust it.',
        spot: [
            'A charge you do not recognise, a "cancel within 24 hours" line, and a phone number as the only action.',
            'When you ring, they ask to install remote support software to "process the refund".',
        ],
        eg: 'A PDF "renewal confirmation" for €499 of antivirus, with a helpline that walks you into a refund scam.',
        keys: 'callback phishing toad fake invoice subscription renewal phone number to cancel refund scam antivirus charge',
    },

    /* =============================================================== MONEY == */
    {
        id: 'bec',
        term: 'Business email compromise',
        also: ['BEC'],
        glyph: '🏢',
        cat: 'money',
        aud: 'both',
        what: 'An attacker gets into (or convincingly imitates) a real business mailbox and uses genuine conversations to redirect a genuine payment. There is usually no malware at all, which is why it beats most defences and costs more than ransomware.',
        spot: [
            'A change of bank details on an invoice you were expecting anyway.',
            'A reply that arrives in a real thread but from a slightly different address, or with the reply-to quietly changed.',
            'Pressure to skip the callback: "I’m in meetings all day, just process it."',
            'Mailbox rules that move a supplier’s mail to Archive so the real person never sees the correction.',
        ],
        eg: 'Two weeks of silent mailbox access, then a message in the existing thread: "Our account is under audit, please use the new IBAN below for this month’s invoice."',
        keys: 'bec business email compromise invoice fraud payment redirect changed bank details iban changed supplier fraud ceo fraud wire transfer',
    },
    {
        id: 'ceo-fraud',
        term: 'CEO fraud',
        also: ['fake president fraud'],
        glyph: '👔',
        cat: 'money',
        aud: 'both',
        what: 'A specific flavour of BEC: someone claiming to be a senior executive asks a junior finance person for an urgent, confidential, out-of-process payment.',
        spot: [
            'Urgency plus secrecy plus seniority in a single message. That combination is the fraud.',
            'A first-ever request of this kind, made by a channel the executive does not normally use.',
            'The reply-to address differs from the display name.',
        ],
        eg: '"I’m in a confidential acquisition and cannot discuss it. Transfer €48,000 to the account below today. Do not copy anyone."',
        keys: 'ceo fraud fake ceo boss asked me to pay urgent transfer gift cards for boss president fraud confidential payment',
    },
    {
        id: 'invoice-fraud',
        term: 'Invoice fraud',
        also: ['mandate fraud', 'payment diversion'],
        glyph: '🧾',
        cat: 'money',
        aud: 'both',
        what: 'A real supplier relationship, a real invoice, and a fraudulent set of bank details. The money goes out through your normal, approved process, which is exactly why it is rarely stopped.',
        spot: [
            '**Any** change of bank details, ever, from any supplier. Treat this as a red alert, always, with no exceptions.',
            'A "new finance system" or "account under audit" explanation.',
            'The new account is in a different country, or the account name does not match the company name.',
        ],
        eg: 'A letter on perfect headed paper announcing your builder has changed bank. The builder knows nothing about it.',
        keys: 'invoice fraud mandate fraud changed bank details new iban supplier changed account paid wrong account payment diverted',
    },
    {
        id: 'card-fraud',
        term: 'Card fraud',
        glyph: '💳',
        cat: 'money',
        aud: 'user',
        what: 'Someone uses your card details without the card. Details come from a fake shop, a skimmer, a data breach, or a phishing page. Card fraud is the one crime where the rules are strongly on your side — if you report it promptly.',
        spot: [
            'A small test payment (€0.50–€5) before a large one. Never ignore a small charge you do not recognise.',
            'Charges in a currency or country you have no connection to.',
            'A refused payment you did not make.',
        ],
        eg: 'A €1.02 charge to an unfamiliar online service on Tuesday, and €780 of electronics on Wednesday.',
        keys: 'card fraud stolen card details unauthorised transaction money gone from my account charges i did not make small test charge',
    },
    {
        id: 'apr-fraud',
        term: 'Authorised push payment fraud',
        also: ['APP fraud', 'bank transfer scam'],
        glyph: '➡️',
        cat: 'money',
        aud: 'user',
        what: 'You were tricked into pressing send yourself. Because you authorised it, it is legally different from card fraud and much harder to reverse — though in several countries banks must now reimburse victims in many cases. Report it in minutes, not hours.',
        spot: [
            'Any request to move money to a "safe account". No bank has ever done this. It is always a scam, with no exceptions.',
            'A payee name that does not match the account holder, and a warning you were encouraged to click past.',
        ],
        eg: 'A "fraud officer" keeps you on the line while you transfer your balance to an account he says is in your own name. It is not.',
        keys: 'app fraud authorised push payment bank transfer scam i transferred the money safe account sent money to scammer reimbursement',
    },
    {
        id: 'pig-butchering',
        term: 'Pig butchering',
        also: ['romance investment scam', 'sha zhu pan'],
        glyph: '🥩',
        cat: 'money',
        aud: 'user',
        what: 'A long-game investment scam. Weeks or months of real friendship or romance, then an introduction to a trading or crypto platform that shows fake profits until you try to withdraw. The name is the criminals’ own: fattening the pig before slaughter.',
        spot: [
            'A wrong-number message that turns into a warm conversation.',
            'Wealth signalled early and casually, then an "opportunity" you did not ask about.',
            'A platform only they can introduce you to, with an app installed outside the official stores.',
            'Small withdrawals succeed. Large ones require "tax", "fees" or "liquidity" first. That money is gone too.',
        ],
        eg: 'Four months of daily messages, a €500 test that returns €610, then €40,000 that can only be released after a €9,000 "capital gains deposit".',
        keys: 'pig butchering romance scam crypto investment scam trading platform fake profits cannot withdraw dating scam love scam wrong number message',
    },
    {
        id: 'advance-fee',
        term: 'Advance fee fraud',
        also: ['419 scam'],
        glyph: '🎁',
        cat: 'money',
        aud: 'user',
        what: 'A large sum is promised — inheritance, lottery, compensation, a released parcel — but a smaller payment must be made first. There is never only one fee.',
        spot: ['You are asked to pay to receive money. Real windfalls deduct costs; they do not invoice you.'],
        eg: 'A "compensation fund for scam victims" that needs a €250 processing fee. The list of previous victims is where they got your name.',
        keys: 'advance fee 419 nigerian prince lottery win inheritance fee first pay to receive compensation scam recovery',
    },
    {
        id: 'recovery-scam',
        term: 'Recovery scam',
        glyph: '🔁',
        cat: 'money',
        aud: 'user',
        what: 'Being scammed a second time by someone offering to get back what you lost the first time. Victim lists are traded between criminals; a first loss makes you a marked target.',
        spot: [
            'They contacted you, and they already know you were a victim.',
            'They claim to be a "fund recovery agency", a blockchain investigator, or even a police unit — and ask for an up-front fee.',
            'Real police, real banks and real regulators never charge you to recover your own money.',
        ],
        eg: 'Three weeks after a crypto loss, a "certified asset recovery specialist" offers a 30% success fee, plus €1,200 up front for the court filing.',
        keys: 'recovery scam scammed twice get my money back fund recovery agency crypto recovery second scam victim list',
    },
    {
        id: 'sextortion',
        term: 'Sextortion',
        glyph: '🚫',
        cat: 'money',
        aud: 'user',
        what: 'A threat to publish intimate images unless you pay. It comes in two very different forms: the mass-mailed bluff, where nothing exists, and the real case, where images were actually obtained. Both are crimes, and neither is your fault.',
        spot: [
            '**The bluff:** an old password from a data breach quoted as "proof", claims of webcam footage, a bitcoin address, a 48-hour deadline. Delete it. There is no footage.',
            '**The real one:** a conversation on a dating app or game that moved fast to video, followed by immediate demands.',
            'Paying never ends it. It marks you as someone who pays.',
        ],
        eg: '"I have recorded you through your camera. Your password is hunter2. Send $1,400 in bitcoin within 48 hours." The password is from a breach a decade old.',
        keys: 'sextortion blackmail nude photos webcam blackmail email bitcoin threat leaked images they have my password threatening to send to my contacts',
    },
    {
        id: 'gift-card-scam',
        term: 'Gift card scam',
        glyph: '🎟',
        cat: 'money',
        aud: 'user',
        what: 'Being asked to pay with retail gift cards and read out the codes. Gift cards are untraceable, instantly resold and completely irreversible — which is why they are the payment method of no legitimate organisation on earth.',
        spot: ['**Nobody legitimate is ever paid in gift cards.** Not the tax office, not the police, not your employer, not a utility, not a helpdesk. This one rule ends the scam on the spot.'],
        eg: '"The CEO is in a board meeting and needs €600 of Apple gift cards for client gifts. Buy them and photograph the backs."',
        keys: 'gift card scam itunes cards steam cards apple cards asked to buy gift cards codes read out boss asked for gift cards',
    },
    {
        id: 'task-scam',
        term: 'Task scam',
        also: ['job scam', 'app-rating scam'],
        glyph: '📝',
        cat: 'money',
        aud: 'user',
        what: 'A "remote job" that pays you small amounts for meaningless tasks — liking videos, rating apps, boosting listings — until your account goes negative and you must deposit your own money to unlock your earnings.',
        spot: [
            'Recruitment by unsolicited WhatsApp or Telegram message.',
            'You have to top up your own balance to "complete a combination task".',
            'Early withdrawals work. That is the hook, not the proof.',
        ],
        eg: '€38 earned in the first hour, then a "merchant task" that requires €300 of your own funds to release €412.',
        keys: 'task scam job scam whatsapp job offer telegram job app rating deposit to withdraw fake employment easy money online',
    },
    {
        id: 'marketplace-scam',
        term: 'Marketplace scam',
        glyph: '🛒',
        cat: 'money',
        aud: 'user',
        what: 'Fraud around second-hand selling sites: the fake "payment link" sent to a seller, the item that never ships to a buyer, the courier who needs a fee.',
        spot: [
            'A **buyer** who sends you a link to "receive" your money. Receiving money never requires you to log in or enter a card.',
            'Anyone insisting on moving off-platform immediately.',
            'A price that only makes sense if the item does not exist.',
        ],
        eg: 'A buyer for your sofa sends a convincing "secure payout" link. It is a bank login page that drains the account it is meant to fill.',
        keys: 'marketplace scam facebook marketplace vinted ebay selling scam payment link buyer scam item never arrived second hand',
    },
    {
        id: 'fake-shop',
        term: 'Fake webshop',
        glyph: '🏪',
        cat: 'money',
        aud: 'user',
        what: 'A shop that exists to collect card details and orders, not to send goods. Often a cloned design, a stolen product catalogue and a domain registered weeks ago.',
        spot: [
            'Bank transfer, crypto or "friends and family" as the only real payment option.',
            'No verifiable company address, VAT number or phone; contact only via a web form.',
            'Prices far below everyone else on an item that is in demand.',
            'Reviews that are all five stars, all recent, and all similarly phrased.',
        ],
        eg: 'A "clearance outlet" selling a €900 games console for €310, accepting cards, delivering nothing, and offline within a fortnight.',
        keys: 'fake shop fake webshop scam website bought something never arrived online shopping scam too cheap fake store',
    },

    /* =========================================================== TECHNICAL == */
    {
        id: 'malware',
        term: 'Malware',
        glyph: '🦠',
        cat: 'technical',
        aud: 'both',
        what: 'Any software written to work against the interests of the person running it. The umbrella over viruses, ransomware, infostealers, remote access tools and spyware.',
        spot: ['A file that must be run, unzipped-then-run, or "enabled", to show you something that should have been just a document or a picture.'],
        eg: 'A ZIP containing `Invoice_2026.pdf.lnk` — a shortcut, not a PDF, which quietly launches PowerShell.',
        keys: 'malware virus infected computer trojan malicious software got a virus computer infected',
    },
    {
        id: 'infostealer',
        term: 'Infostealer',
        also: ['stealer', 'credential stealer'],
        glyph: '🧲',
        cat: 'technical',
        aud: 'both',
        what: 'Malware whose whole job is a single sweep: every saved browser password, every session cookie, crypto wallets, VPN configs and documents, packaged and uploaded within seconds. It often deletes itself afterwards, so the machine looks clean.',
        spot: [
            'Frequently arrives via cracked software, game cheats, fake browser updates and "ClickFix" copy-paste prompts.',
            'The infection is over in seconds; the damage is every credential ever saved in that browser.',
            'Because it steals **session cookies**, the attacker can log in without your password and without triggering MFA.',
        ],
        eg: 'A "fix your video codec" prompt tells you to paste a command into the Run box. Two seconds later your saved passwords are in a Telegram channel.',
        keys: 'infostealer stealer redline lumma raccoon saved passwords stolen browser passwords cookies stolen cracked software game cheat',
    },
    {
        id: 'clickfix',
        term: 'ClickFix',
        also: ['fake CAPTCHA', 'paste-and-run'],
        glyph: '📋',
        cat: 'technical',
        aud: 'both',
        what: 'A page that tells you to prove you are human, or fix an error, by copying something and pasting it into the Windows Run box, a terminal, or PowerShell. You become the delivery mechanism, so no download is ever blocked.',
        spot: [
            '**No legitimate website has ever needed you to paste a command anywhere to view it.** Not one. This alone identifies the attack.',
            'Instructions naming Win+R, Terminal, PowerShell, or a keyboard shortcut you would not otherwise use.',
            'A CAPTCHA with extra steps.',
        ],
        eg: '"Verification failed. Press Windows + R, paste, and press Enter to continue." The clipboard already contains a one-line downloader.',
        keys: 'clickfix fake captcha paste command powershell run box win+r copy paste verification i pasted something told me to press windows r',
    },
    {
        id: 'ransomware',
        term: 'Ransomware',
        glyph: '🔒',
        cat: 'technical',
        aud: 'both',
        what: 'Malware that encrypts your files and demands payment for the key. Modern crews steal the data first and threaten to publish it, so backups alone no longer end the story.',
        spot: [
            'Files renamed with a new extension; a ransom note in every folder.',
            'Backups, shadow copies and cloud sync all failing or already wiped — that is done deliberately, first.',
            'Slow, spreading breakage rather than one broken machine.',
        ],
        eg: 'Every document becomes `report.docx.locked` and each folder gains `HOW_TO_RESTORE.txt`.',
        keys: 'ransomware files encrypted ransom note cannot open files locked files extension changed pay to decrypt cryptolocker',
    },
    {
        id: 'rat',
        term: 'Remote access trojan',
        also: ['RAT'],
        glyph: '🖥',
        cat: 'technical',
        aud: 'both',
        what: 'Malware that hands live control of your device to someone else — screen, keyboard, files, camera, and any session you are already logged into.',
        spot: [
            'The pointer moving on its own; windows opening; the screen going black "for maintenance" while something happens.',
            'Legitimate remote support tools you did not install: AnyDesk, TeamViewer, ScreenConnect, UltraViewer, Quick Assist.',
        ],
        eg: 'A "bank fraud officer" has you install AnyDesk, then blanks your screen while emptying the account you left logged in.',
        keys: 'rat remote access trojan someone controlling my computer anydesk teamviewer remote support installed mouse moving on its own',
    },
    {
        id: 'keylogger',
        term: 'Keylogger',
        glyph: '⌨️',
        cat: 'technical',
        aud: 'both',
        what: 'Records everything typed — passwords, messages, card numbers. Can be software, or a small hardware device between keyboard and computer.',
        spot: ['Rarely visible. Assume one after any confirmed compromise and change passwords from a **different, clean device**, not the affected one.'],
        eg: 'Changing your password on the infected machine simply tells the attacker the new one.',
        keys: 'keylogger keystroke logger typing recorded password captured hardware keylogger spyware',
    },
    {
        id: 'stalkerware',
        term: 'Stalkerware',
        also: ['spouseware'],
        glyph: '👁',
        cat: 'technical',
        aud: 'user',
        what: 'Monitoring software installed on a phone by someone who has physical access to it — usually a partner, ex-partner or family member. It reports location, messages and calls.',
        spot: [
            'Battery draining unusually fast, heat when idle, unexplained data use.',
            'A phone that was "set up for you" by someone else, or a shared family account you did not configure.',
            '**If you are at risk of domestic abuse, removing it can escalate danger.** Contact a domestic-violence support service before changing anything.',
        ],
        eg: 'A partner always knows where you have been and what you texted, and your phone has an unfamiliar device-administrator app.',
        keys: 'stalkerware spouseware partner tracking me phone monitored location shared domestic abuse spying app',
    },
    {
        id: 'aitm',
        term: 'Adversary-in-the-middle',
        also: ['AiTM', 'man-in-the-middle', 'MitM', 'reverse proxy phishing'],
        glyph: '🪞',
        cat: 'technical',
        aud: 'both',
        what: 'A phishing site that sits between you and the real one, relaying everything live. You see the genuine login, the genuine MFA prompt and the genuine "welcome back" — because it is genuine. The attacker keeps the session cookie at the end.',
        spot: [
            'Nothing looks wrong. That is the defining feature.',
            'The only reliable clue is the domain in the address bar before you type anything.',
            'This is why **codes and push approvals do not stop phishing, and passkeys do**: a passkey is bound to the real domain and simply will not work on the proxy.',
        ],
        eg: 'You log in, approve the push, land on the real inbox — and the attacker is already in your mailbox using the stolen cookie, without your password.',
        keys: 'aitm adversary in the middle man in the middle evilginx mfa bypassed session cookie stolen logged in anyway proxy phishing',
    },
    {
        id: 'session-hijacking',
        term: 'Session hijacking',
        also: ['token theft', 'cookie theft', 'pass-the-cookie'],
        glyph: '🍪',
        cat: 'technical',
        aud: 'both',
        what: 'Stealing the token your browser holds after you log in, and replaying it. It works without your password and without any MFA prompt, because from the service’s point of view you already authenticated.',
        spot: [
            'Sign-in activity from an impossible location with **no** failed attempts and no MFA challenge.',
            'This is why a password change alone is not enough. You must **revoke sessions** as well, or the attacker stays inside.',
        ],
        eg: 'You reset your password at 10:04 and the attacker keeps reading your mail until 17:00, because nobody signed the old session out.',
        keys: 'session hijack token theft cookie theft pass the cookie still logged in after password change revoke sessions sign out everywhere',
    },
    {
        id: 'mfa-fatigue',
        term: 'MFA fatigue',
        also: ['push bombing', 'MFA bombing'],
        glyph: '🔔',
        cat: 'technical',
        aud: 'both',
        what: 'The attacker already has your password and simply requests approval over and over — at 3am, during a meeting, for twenty minutes — until you approve one to make it stop.',
        spot: [
            'Any approval prompt you did not personally trigger, even one, means someone has your password. Deny it and change the password immediately.',
            'A follow-up call from "IT" apologising for the prompts and asking you to accept the next one. That call is the attacker.',
        ],
        eg: 'Forty push notifications overnight; the forty-first is approved half-asleep, and that is the whole breach.',
        keys: 'mfa fatigue push bombing approval prompts spammed accepted a prompt by accident authenticator notifications did not request',
    },
    {
        id: 'sim-swap',
        term: 'SIM swap',
        also: ['SIM hijacking', 'port-out fraud'],
        glyph: '📵',
        cat: 'technical',
        aud: 'both',
        what: 'Getting your mobile number transferred to the attacker’s SIM. Every SMS code, every "call us to verify", every phone-based reset then goes to them.',
        spot: [
            '**Your phone suddenly loses all signal** and stays that way while others nearby are fine. That is the alarm — act within minutes.',
            'An unexpected "your number has been transferred" or porting confirmation.',
        ],
        eg: 'Signal drops on a Friday evening; by Saturday morning three accounts have been reset by SMS and the bank has been drained.',
        keys: 'sim swap sim hijack lost signal no service phone number stolen ported sms codes going elsewhere esim fraud',
    },
    {
        id: 'credential-stuffing',
        term: 'Credential stuffing',
        glyph: '🔑',
        cat: 'technical',
        aud: 'both',
        what: 'Taking username and password pairs from one site’s breach and trying them everywhere else. It costs the attacker almost nothing and works whenever a password has been reused.',
        spot: [
            'Login alerts on accounts you barely use, spread across many services at once.',
            'The fix is not a better password; it is a **different** password on every site.',
        ],
        eg: 'A forum breached in 2019 gives an attacker the same email and password that still open your streaming, delivery and store accounts today.',
        keys: 'credential stuffing password reuse same password everywhere breached password tried on other sites account takeover',
    },
    {
        id: 'password-spraying',
        term: 'Password spraying',
        glyph: '🚿',
        cat: 'technical',
        aud: 'pro',
        what: 'Trying a handful of very common passwords against a very large number of accounts, slowly, so lockout thresholds never trigger.',
        spot: ['A low count of failed logins spread widely across accounts, often from many source addresses, often against legacy protocols.'],
        eg: '`Summer2026!` tried once against 4,000 accounts. Statistically, some of them work.',
        keys: 'password spraying spray attack common passwords many accounts failed logins legacy auth',
    },
    {
        id: 'oauth-consent',
        term: 'Malicious OAuth consent',
        also: ['illicit consent grant', 'app consent phishing'],
        glyph: '✅',
        cat: 'technical',
        aud: 'both',
        what: 'Instead of stealing your password, the attacker asks you to grant an app permission to read your mail or files. You click Accept on a real, genuine consent screen — and the access survives password changes and MFA.',
        spot: [
            'A consent prompt from an app you do not recognise asking to "read your mail", "access your files" or "maintain access to data you have given it access to".',
            'Because you approved it, resetting your password does nothing. The grant must be revoked separately.',
        ],
        eg: 'A "PDF Viewer Pro" invitation asks for offline mailbox access. Access continues for months after the password is changed.',
        keys: 'oauth consent malicious app granted permissions third party app access mail app consent phishing revoke app access azure app',
    },
    {
        id: 'juice-jacking',
        term: 'Juice jacking',
        glyph: '🔌',
        cat: 'technical',
        aud: 'user',
        what: 'A public USB charging port (airport, hotel, train) that also carries data and attempts to pair with your phone. The risk is real but rare and modern phones ask before trusting a computer.',
        spot: ['A charging port that produces a "Trust this computer?" or "Allow data access?" prompt. Say no, always.'],
        eg: 'A hotel lobby charging locker with a modified cable that tries to establish a data connection.',
        keys: 'juice jacking public usb charging airport charger hotel charging cable data blocker trust this computer',
    },
    {
        id: 'evil-twin',
        term: 'Evil twin Wi-Fi',
        also: ['rogue access point'],
        glyph: '📶',
        cat: 'technical',
        aud: 'user',
        what: 'A Wi-Fi network named to look like the real one — "Airport_Free_WiFi", "Hotel Guest 2" — run by someone who then sees or manipulates the traffic that is not properly encrypted.',
        spot: [
            'Two networks with almost the same name; the stronger, open one is the suspicious one.',
            'A captive portal asking for an email password, a card number, or a "certificate" to install.',
            'Modern HTTPS blunts most of this. The real risk is the fake login portal and the certificate you are asked to accept.',
        ],
        eg: 'A café network with no password whose sign-in page asks you to "log in with your email provider" to get online.',
        keys: 'evil twin fake wifi rogue access point public wifi hotspot airport wifi hotel wifi captive portal is public wifi safe',
    },
    {
        id: 'deepfake',
        term: 'Deepfake',
        also: ['synthetic media', 'voice cloning'],
        glyph: '🎭',
        cat: 'technical',
        aud: 'both',
        what: 'Synthetic audio or video of a real person. A convincing voice clone now needs only a few seconds of source audio — a voicemail greeting, a podcast, a social post — and works well enough on a phone call to move money.',
        spot: [
            'Live video and live voice are no longer proof of identity. Verification must be done on a **separate, known channel** you initiate.',
            'Ask something only the real person would know and could not have posted publicly. Agree a family code word in advance.',
            'Pressure to act before you can call back is the tell, not the audio quality.',
        ],
        eg: 'A grandparent gets a call in their grandchild’s voice, crying, from a "police station", needing bail money immediately.',
        keys: 'deepfake voice clone ai voice fake video fake call sounded like my son ai scam synthetic voice video call fraud',
    },
    {
        id: 'spoofing',
        term: 'Spoofing',
        glyph: '🎪',
        cat: 'technical',
        aud: 'both',
        what: 'Forging the "from" of anything — email address, caller ID, SMS sender name, website. Nothing you can see in a From field, a caller display or an SMS thread proves who sent it.',
        spot: [
            'Caller ID showing your bank’s real number. It is free to forge and means nothing.',
            'A spoofed SMS lands in the same thread as genuine ones from that brand.',
            'The display name is right, the underlying address is wrong. Always expand it.',
        ],
        eg: 'A text in your existing bank thread, under the bank’s real sender name, warning of a payment and giving a link.',
        keys: 'spoofing spoofed caller id fake number fake sender same thread as real messages email spoofing display name',
    },
    {
        id: 'spf-dkim-dmarc',
        term: 'SPF, DKIM and DMARC',
        glyph: '📜',
        cat: 'defence',
        aud: 'both',
        what: 'Three email records that let a domain owner say which servers may send mail as them (SPF), sign it cryptographically (DKIM), and tell receivers what to do when neither passes (DMARC). Together they stop others sending mail **as your exact domain**.',
        spot: [
            'They do **not** stop lookalike domains, display-name spoofing, or a genuinely compromised mailbox — which is where most real fraud comes from.',
            'A DMARC policy of `p=none` is monitoring only. It blocks nothing until it reaches `p=reject`.',
        ],
        eg: 'DMARC at reject stops `@yourcompany.com` being forged, so the attacker registers `@yourcompany-invoices.com` instead.',
        keys: 'spf dkim dmarc email authentication p=reject spoofing protection dns records email security domain',
    },
    {
        id: 'data-breach',
        term: 'Data breach',
        glyph: '🕳',
        cat: 'technical',
        aud: 'both',
        what: 'A company holding your data loses control of it. Your exposure depends entirely on what was taken: an email address is a nuisance, a password is urgent, a passport scan or bank details are serious and long-lived.',
        spot: [
            'Read what was actually taken before reacting. "We have no evidence of misuse" is not the same as "nothing was taken".',
            'Expect targeted phishing afterwards that quotes real details from the breach to sound legitimate.',
            'Breached passwords matter on **every site where you reused them**, not just the one that was breached.',
        ],
        eg: 'A retailer loses order history and addresses. Six weeks later customers receive delivery texts quoting their real last order.',
        keys: 'data breach my data leaked company hacked my details stolen breach notification have i been pwned password leaked',
    },
    {
        id: 'doxxing',
        term: 'Doxxing',
        glyph: '📍',
        cat: 'technical',
        aud: 'user',
        what: 'Publishing someone’s private details — address, workplace, phone, family — to enable harassment. Usually assembled from public sources rather than hacked.',
        spot: ['Data brokers, old forum posts, property records, photo metadata and delivery-tracking pages are the usual sources.'],
        eg: 'A photo posted with location data intact, combined with an old CV, gives a harasser a home address.',
        keys: 'doxxing doxed personal details published address leaked harassment stalking my info online',
    },

    /* ============================================================= DEFENCE == */
    {
        id: 'mfa',
        term: 'Multi-factor authentication',
        also: ['MFA', '2FA', 'two-step verification'],
        glyph: '🔐',
        cat: 'defence',
        aud: 'both',
        what: 'Needing a second thing beyond your password. Not all second factors are equal, and the difference matters enormously.',
        spot: [
            '**SMS codes** — better than nothing, defeated by SIM swap and by any phishing page that asks for the code.',
            '**App codes (TOTP)** — better, but still typeable into a fake site.',
            '**Push approval** — convenient, defeated by MFA fatigue unless it uses number matching.',
            '**Passkeys and security keys** — phishing-resistant. They check the real domain themselves, so they cannot be handed to a fake site at all.',
        ],
        eg: 'A person with an app code can still be phished. A person with a passkey cannot complete the login on the fake domain, and the attack simply fails.',
        keys: 'mfa 2fa two factor authentication second factor authenticator app sms code security key which mfa is best',
    },
    {
        id: 'passkey',
        term: 'Passkey',
        also: ['FIDO2', 'WebAuthn'],
        glyph: '🗝',
        cat: 'defence',
        aud: 'both',
        what: 'A login secret stored on your device and unlocked by your face, fingerprint or device PIN. Nothing is typed, nothing is sent, and it only works on the exact domain it was created for.',
        spot: [
            'Because the browser checks the domain, a phishing site cannot use it — this is the single biggest upgrade available to a normal person.',
            'Passkeys sync through your Apple, Google or password-manager account, so a lost phone is not a lockout.',
            'Turn it on for email first. Email is the master key to everything else.',
        ],
        eg: 'A perfect copy of your bank’s login page cannot trigger your passkey, because the passkey is bound to the real domain and refuses to appear.',
        keys: 'passkey passkeys fido2 webauthn security key yubikey passwordless face id fingerprint login phishing resistant',
    },
    {
        id: 'password-manager',
        term: 'Password manager',
        glyph: '🧰',
        cat: 'defence',
        aud: 'both',
        what: 'An app that generates and stores a different long password for every site. Its quiet superpower is anti-phishing: it refuses to autofill on the wrong domain, so it notices fake sites that you would not.',
        spot: [
            '**If your manager does not offer to fill, stop and check the address.** That silence is a warning, not a bug.',
            'One strong, memorable master passphrase plus MFA on the vault itself.',
            'Store recovery codes in it too, not in your email.',
        ],
        eg: 'You land on a convincing lookalike; the manager stays silent; that hesitation saves the account.',
        keys: 'password manager bitwarden 1password keepass vault autofill unique passwords master password store passwords safely',
    },
    {
        id: 'vcc',
        term: 'Virtual card number',
        also: ['single-use card', 'disposable card', 'burner card'],
        glyph: '🎫',
        cat: 'defence',
        aud: 'user',
        what: 'A card number that is not your real one. Many banks and fintechs will issue one per merchant, or one that can be used a single time, sometimes with a spending cap and an expiry. If the shop is fake or later breached, the number is worthless and your real card never has to be replaced.',
        spot: [
            'Look for "virtual card", "disposable card", "card generator", "merchant-locked card" in your banking app.',
            'Apple Pay, Google Pay and Click to Pay give a similar benefit by sending a device token instead of your real number.',
            'Best used for: unfamiliar shops, free trials, subscriptions you expect to fight to cancel.',
            'Watch the practicalities: refunds must go back to the same virtual number, and hotels or car hire may want the physical card at the desk.',
        ],
        eg: 'A €40-capped, merchant-locked virtual number used at an unknown shop. The shop is breached; the number is declined everywhere else and no card is reissued.',
        keys: 'virtual card number one time use card disposable card burner card single use card number revolut privacy.com apple pay safe online shopping',
    },
    {
        id: '3ds',
        term: '3-D Secure',
        also: ['Verified by Visa', 'Mastercard Identity Check', 'SCA'],
        glyph: '🛂',
        cat: 'defence',
        aud: 'user',
        what: 'The step where your bank app confirms an online card payment. It blocks a stolen card number from being used without your phone — but it is also exactly what a scammer will try to talk you through.',
        spot: [
            '**Read the amount and the merchant name in the approval prompt every single time.** That is the whole point of the step.',
            'Never approve a prompt because someone on the phone asked you to. Never read the code out loud to anyone.',
        ],
        eg: 'A "fraud officer" says: "approve the prompt so we can cancel the payment." Approving the prompt **is** the payment.',
        keys: '3d secure verified by visa sca strong customer authentication payment approval bank app confirm payment code',
    },
    {
        id: 'chargeback',
        term: 'Chargeback',
        glyph: '↩️',
        cat: 'defence',
        aud: 'user',
        what: 'A card scheme process to reverse a payment — for fraud, for goods that never arrived, or for a merchant that will not refund. It is the strongest consumer protection in ordinary life, and it is why paying by card beats paying by bank transfer.',
        spot: [
            'Time limits apply (often 120 days from the transaction or expected delivery). Do not sit on it.',
            'It only exists for card payments. Bank transfers, crypto and gift cards have no equivalent.',
        ],
        eg: 'Goods never arrive from a fake shop; the card issuer reverses the charge; the same loss by bank transfer would be permanent.',
        keys: 'chargeback dispute a payment reverse a transaction refund card protection section 75 never arrived get money back',
    },
    {
        id: 'credit-freeze',
        term: 'Credit freeze',
        also: ['security freeze', 'protective registration'],
        glyph: '🧊',
        cat: 'defence',
        aud: 'user',
        what: 'Blocking new credit applications in your name. Names and mechanisms differ by country — a freeze in the US, CIFAS protective registration in the UK, a fraud notice with the national credit register elsewhere — but the goal is the same: stop someone opening accounts as you.',
        spot: ['Do this after identity documents are exposed, not after a single card is misused.'],
        eg: 'A stolen passport scan surfaces on a forum; a freeze prevents three loan applications the following month.',
        keys: 'credit freeze security freeze cifas identity theft protection stop loans in my name credit report fraud alert',
    },
    {
        id: 'code-word',
        term: 'Family code word',
        glyph: '🗣',
        cat: 'defence',
        aud: 'user',
        what: 'A word agreed in advance, in person, that a real family member can say and a voice clone cannot. Free, instant, and the only defence that still works when the voice is perfect.',
        spot: ['Choose something unguessable and never written down online. Teach it to older relatives especially — they are targeted hardest.'],
        eg: '"Grandma, it’s me, I’ve been in an accident." — "What’s the word?" ends the call in one second.',
        keys: 'code word safe word family password voice clone protection grandparent scam ai voice defence agree in advance',
    },

    /* ================================================================= PRO == */
    {
        id: 'ioc',
        term: 'Indicator of compromise',
        also: ['IOC'],
        glyph: '🔬',
        cat: 'pro',
        aud: 'pro',
        what: 'An observable artefact suggesting an intrusion: a hash, a domain, an IP, a user agent, a mailbox rule name, a registry key. Cheap to hunt, cheap for the adversary to change.',
        spot: ['IOCs age fast. Behaviour and TTPs survive infrastructure rotation; a hash rarely survives the week.'],
        eg: 'The AiTM landing domain is burned within hours; the pattern of "new inbox rule moving mail to RSS Feeds" is reused for years.',
        keys: 'ioc indicator of compromise hash domain ip artefact hunting pyramid of pain',
    },
    {
        id: 'ttp',
        term: 'TTPs',
        also: ['tactics, techniques and procedures'],
        glyph: '🧩',
        cat: 'pro',
        aud: 'pro',
        what: 'How an adversary operates rather than what they used. Mapped in practice to MITRE ATT&CK technique IDs, which give everyone a shared vocabulary and a detection checklist.',
        spot: ['Map every confirmed incident to ATT&CK during the review. Gaps in coverage show up as clusters of unmapped techniques.'],
        eg: 'T1566.002 (spearphishing link) → T1539 (steal web session cookie) → T1114 (email collection) → T1114.003 (email forwarding rule).',
        keys: 'ttp tactics techniques procedures mitre attack technique id detection mapping',
    },
    {
        id: 'kill-chain',
        term: 'Kill chain',
        glyph: '⛓',
        cat: 'pro',
        aud: 'pro',
        what: 'The staged model of an intrusion — recon, delivery, exploitation, installation, command and control, actions on objectives. Useful chiefly for asking "what came before this, and what comes next?"',
        spot: ['If you are looking at C2, delivery already happened and you have not found it yet. Work backwards as hard as forwards.'],
        eg: 'An EDR alert on credential access implies successful delivery and execution hours or days earlier.',
        keys: 'kill chain cyber kill chain stages intrusion model lockheed',
    },
    {
        id: 'dwell-time',
        term: 'Dwell time',
        glyph: '⏳',
        cat: 'pro',
        aud: 'pro',
        what: 'How long the adversary was present before detection. It sets the scope of everything: which credentials to treat as burned, how far back to pull logs, and how much you must assume rather than prove.',
        spot: ['Anchor dwell time to the earliest **credible** evidence, not the first alert. Log retention often becomes the real limit.'],
        eg: 'Sign-in logs retained 30 days, first anomalous grant at day 29 — you cannot prove day 31 was clean, so scope conservatively.',
        keys: 'dwell time time to detect scope log retention how long were they in',
    },
    {
        id: 'containment',
        term: 'Containment',
        glyph: '🧱',
        cat: 'pro',
        aud: 'pro',
        what: 'Stopping the spread and the bleeding before you understand the whole picture. Deliberately traded against evidence preservation and against tipping off the adversary.',
        spot: [
            'Isolate rather than power off: RAM and live sessions die with the machine.',
            'For identity incidents, revoking sessions and refresh tokens matters more than resetting the password.',
            'Partial containment can be worse than none — it teaches the adversary what you can see.',
        ],
        eg: 'Network-isolate the endpoint in EDR, keep it running, snapshot, then collect volatile data.',
        keys: 'containment isolate contain quarantine revoke sessions disable account stop the spread',
    },
    {
        id: 'eradication',
        term: 'Eradication and recovery',
        glyph: '🧹',
        cat: 'pro',
        aud: 'pro',
        what: 'Removing every foothold, then restoring service. Eradication fails when it removes malware but leaves persistence: an OAuth grant, a rogue MFA method, a forwarding rule, an API key, a scheduled task.',
        spot: ['Write the persistence checklist before you start, and sign it off item by item. Reinfection is nearly always a missed foothold, not a new intrusion.'],
        eg: 'A rebuilt laptop is reinfected in a day because the attacker’s app consent grant on the identity was never revoked.',
        keys: 'eradication recovery remove persistence rebuild reimage foothold reinfection cleanup',
    },
    {
        id: 'blast-radius',
        term: 'Blast radius',
        glyph: '💥',
        cat: 'pro',
        aud: 'pro',
        what: 'Everything a single compromised identity or host could reach. The first question of any triage, and usually much larger than it looks.',
        spot: ['Enumerate: mailbox and delegates, shared mailboxes, files and shares, SaaS via SSO, saved browser credentials, VPN, admin roles, standing privileges, API keys.'],
        eg: 'One phished user held delegate access to two shared finance mailboxes and an unused Global Reader role.',
        keys: 'blast radius scope impact what could they reach lateral access entitlement review',
    },
    {
        id: 'honeytoken',
        term: 'Honeytoken',
        also: ['canary token'],
        glyph: '🍯',
        cat: 'pro',
        aud: 'pro',
        what: 'A deliberately planted credential, file or account that nobody legitimate should ever touch. Any use is a high-confidence alert with almost no false positives.',
        spot: ['Place them where an attacker looks and a user does not: a fake AWS key in a config file, a decoy admin account, a "passwords.xlsx" on a file share.'],
        eg: 'A decoy `svc_backup_admin` account with no real rights fires an alert the moment it is enumerated.',
        keys: 'honeytoken canary token decoy account trap credential high fidelity alert',
    },
    {
        id: 'tabletop',
        term: 'Tabletop exercise',
        glyph: '🎲',
        cat: 'pro',
        aud: 'pro',
        what: 'A discussion-based rehearsal of an incident with the people who would actually be involved. Its real output is not the scenario — it is the list of things nobody could answer.',
        spot: ['Include legal, comms and an executive decision-maker. The unanswerable questions are almost always about authority and communications, not technology.'],
        eg: '"Who is allowed to take the payroll system offline at 2am on a Sunday?" — an answer that must exist before the night it is needed.',
        keys: 'tabletop exercise rehearsal simulation incident response drill preparedness',
    },
    {
        id: 'chain-of-custody',
        term: 'Chain of custody',
        glyph: '📦',
        cat: 'pro',
        aud: 'pro',
        what: 'The documented, unbroken record of who held each piece of evidence and when. Without it, technically perfect findings can be worthless in a disciplinary hearing, a court or an insurance claim.',
        spot: ['Hash on acquisition, work on copies, log every transfer with time, person and reason. Decide early whether this may become a legal matter — retrofitting is impossible.'],
        eg: 'A memory image with no acquisition hash and no handover log is challenged and excluded.',
        keys: 'chain of custody evidence handling forensics preservation legal hold hashing admissible',
    },
];
