/* ==========================================================================
   Breachlight — data-defend.js
   --------------------------------------------------------------------------
   The bench. What actually reduces your chance of being here again, ordered
   by how much good it does per minute spent.

   Schema
     id       stable, hash-linked, never rename
     title    imperative where possible — the reader is deciding, not browsing
     glyph, cat, aud
     impact   'high' | 'medium'          how much difference it really makes
     effort   'minutes' | 'an evening' | 'ongoing'
     lede     one paragraph, why this and not something else
     steps[]  the checklist — each one tickable, each one an action
     detail[] { h, p[] } the nuance, the trade-offs, the "but what about…"
     keys     search keywords
     terms[]  glossary ids worth reading alongside
   ========================================================================== */

window.BL_DEFEND_CATS = [
    { id: 'accounts', title: 'Accounts and logins', glyph: '🔐' },
    { id: 'verify', title: 'Checking that something is real', glyph: '🔎' },
    { id: 'money', title: 'Money and cards', glyph: '💳' },
    { id: 'device', title: 'Devices and networks', glyph: '📱' },
    { id: 'people', title: 'People around you', glyph: '👨‍👩‍👧' },
    { id: 'org', title: 'If you run the place', glyph: '🏢' },
];

window.BL_DEFEND = [

    /* ============================================================ ACCOUNTS == */
    {
        id: 'email-first',
        title: 'Fortify your email before anything else',
        glyph: '📧',
        cat: 'accounts',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'Your email account is not one account among many. It is the master key: every other service will happily reset its password to whoever controls that inbox. If you only ever do one thing from this whole site, do this one.',
        steps: [
            'Put a **passkey** on your main email account, or a hardware security key if the provider offers one.',
            'Turn off SMS as a recovery method once a stronger factor works — SMS is the weak link a SIM swap exploits.',
            'Give it a password used on **no other site at all**, generated by a password manager.',
            'Print the recovery codes and put them somewhere physical. Do not store them in the inbox they unlock.',
            'Check the recovery phone number and recovery email are still yours, and not an old work address or an ex-partner’s number.',
            'Review connected apps and remove everything you do not currently use.',
            'Check for forwarding rules and filters you did not create. This is the single most common thing an intruder leaves behind.',
        ],
        detail: [
            {
                h: 'Why email outranks even your bank',
                p: [
                    'A bank account can be frozen, reimbursed and reissued. An email account cannot be un-read. Whoever holds it can reset your bank, your government portal, your cloud storage and your social accounts — one after another — while reading the confirmation messages as they arrive.',
                    'It is also where an attacker learns who you bank with, who your accountant is, when you are on holiday and what you have just ordered. That reconnaissance is what turns a generic scam into one that fools you.',
                ],
            },
            {
                h: 'The forwarding-rule check, specifically',
                p: [
                    'In Gmail: Settings → Forwarding and POP/IMAP, and Settings → Filters and blocked addresses.',
                    'In Outlook or Microsoft 365: Settings → Mail → Rules, and Settings → Mail → Forwarding.',
                    'You are looking for anything that forwards externally, or that moves messages containing words like *invoice*, *payment*, *bank* or *password* into Archive, RSS Feeds or Deleted Items. Rules like that exist so that you do not see the replies to messages sent in your name.',
                ],
            },
        ],
        keys: 'email security protect my email account gmail outlook forwarding rules recovery codes master account passkey email',
        terms: ['passkey', 'session-hijacking', 'bec'],
    },
    {
        id: 'password-hygiene',
        title: 'Use a password manager and stop reusing passwords',
        glyph: '🧰',
        cat: 'accounts',
        aud: 'user',
        impact: 'high',
        effort: 'an evening',
        lede: 'The problem was never that your password was too short. It is that the same one opens forty doors, and one of those forty gets breached every year. A manager fixes that, and quietly protects you from phishing as a side effect.',
        steps: [
            'Pick a reputable password manager and set one long master **passphrase** — four or five unrelated words, not a mangled word with a 3 in it.',
            'Turn on MFA for the vault itself.',
            'Do not migrate everything at once. Change passwords as you log in over the next month, starting with email, bank, phone account and anything with a card stored.',
            'Let it generate the passwords. Never look at them; that is the point.',
            'Turn on its breach-monitoring feature and work the list it gives you.',
            'Store recovery codes and answers to "security questions" in the vault too — and make the answers random, not true.',
        ],
        detail: [
            {
                h: 'The anti-phishing superpower nobody mentions',
                p: [
                    'A password manager matches on the domain, not on how the page looks. On a perfect pixel-for-pixel copy of your bank at the wrong address, it simply will not offer to fill.',
                    'So make this a habit: **if the manager does not offer, stop and read the address bar.** That moment of silence catches phishing sites that fool people every single day.',
                ],
            },
            {
                h: '"Isn’t putting all my eggs in one basket risky?"',
                p: [
                    'It is one basket you can watch, encrypt and put a passkey on — versus forty baskets you cannot remember. Every serious assessment lands the same way: a manager is a large net gain.',
                    'Browser-built-in managers are much better than reuse, but they are also exactly what infostealer malware is built to empty in one sweep. A dedicated manager with a locked vault is meaningfully harder to loot.',
                ],
            },
        ],
        keys: 'password manager unique passwords stop reusing passwords bitwarden 1password keepass strong password passphrase generate passwords',
        terms: ['password-manager', 'credential-stuffing', 'infostealer'],
    },
    {
        id: 'mfa-upgrade',
        title: 'Upgrade your second factor to something phishing can’t take',
        glyph: '🗝',
        cat: 'accounts',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'Having "2FA on" is not one thing. An SMS code and a passkey are as different as a chain on the door and a deadbolt. Modern phishing kits defeat codes and push approvals as a matter of routine, and cannot touch passkeys at all.',
        steps: [
            'Add a **passkey** wherever it is offered — email, bank, Microsoft or Google account, social media, password manager.',
            'Where passkeys are not offered, prefer an authenticator app over SMS.',
            'Turn on number matching for push approvals if your provider supports it.',
            'Remove SMS as a factor **only after** a stronger one is confirmed working, and only if it is not your sole recovery route.',
            'Register a second passkey or a backup security key so losing a phone is not a lockout.',
            'Say it out loud once so it sticks: **a code is never read aloud to anybody, for any reason, ever.**',
        ],
        detail: [
            {
                h: 'The ranking, worst to best',
                p: [
                    '**SMS** — beaten by SIM swap and by any fake page that asks you to type the code.',
                    '**Authenticator app (TOTP)** — no SIM-swap risk, but still typeable into a fake site by a helpful victim.',
                    '**Push approval** — no typing, but beaten by MFA fatigue: forty prompts at 3am and one tired thumb.',
                    '**Number matching** — much better; you must read a number off the real screen, so blind approval fails.',
                    '**Passkey or hardware key** — the browser itself verifies the domain. On a phishing site the key does not appear and cannot be used. This is the only rung that structurally cannot be phished.',
                ],
            },
            {
                h: 'Why "the code is never read aloud" is worth memorising',
                p: [
                    'Almost every successful bank-fraud phone call ends with the victim reading a code. The code is not a formality — it is the authorisation for a payment, a device registration or a password reset.',
                    'The message that carries it says so, in the text you are trained to skip. Read the words above the digits before you type them anywhere.',
                ],
            },
        ],
        keys: 'mfa 2fa upgrade passkey security key authenticator app sms codes number matching best two factor phishing resistant',
        terms: ['mfa', 'passkey', 'authenticator-app', 'backup-codes', 'mfa-fatigue', 'aitm'],
    },
    {
        id: 'recovery-paths',
        title: 'Fix your recovery paths before you need them',
        glyph: '🚪',
        cat: 'accounts',
        aud: 'user',
        impact: 'medium',
        effort: 'an evening',
        lede: 'Attackers do not always break the front door — they walk in through the "forgot password" route, which is usually protected far less carefully. It is also the route you will desperately need on the worst day, so it has to be both hard for them and possible for you.',
        steps: [
            'List your critical accounts: email, bank, phone provider, government portal, cloud storage, password manager.',
            'For each, check the recovery email, recovery phone and security questions are current and belong to you.',
            'Remove stale recovery addresses — old employers, old partners, an address you no longer control.',
            'Make security-question answers random strings stored in your vault. Your mother’s maiden name is not a secret.',
            'Download and print recovery codes. Store them offline, away from the devices they protect.',
            'Tell one trusted person where the printed codes are, in case you are unavailable.',
        ],
        detail: [
            {
                h: 'The account nobody thinks about',
                p: [
                    'Your **mobile phone account** is a recovery path for everything else. Add a port-out PIN or account passcode with your carrier so a stranger cannot transfer your number by phoning the shop with your date of birth.',
                    'It takes one call to set up and it is the specific control that defeats SIM swap.',
                ],
            },
        ],
        keys: 'recovery options backup codes forgot password security questions recovery email account lockout port out pin carrier pin',
        terms: ['sim-swap', 'credential-stuffing'],
    },
    {
        id: 'aliases',
        title: 'Give every service a different address',
        glyph: '🎭',
        cat: 'accounts',
        aud: 'user',
        impact: 'medium',
        effort: 'ongoing',
        lede: 'If every site knows the same address, every breach hands attackers the same identifier and half of your login. Different addresses per service break that link, and tell you exactly who leaked you.',
        steps: [
            'Use a private relay or alias feature (Apple Hide My Email, Firefox Relay, a custom-domain catch-all, or plus-addressing as a weak fallback).',
            'Keep one address for banking and government that is used for absolutely nothing else and never posted anywhere.',
            'Use a separate address for shopping and newsletters.',
            'When one alias starts receiving spam or phishing, you know which company leaked. Kill the alias, not the mailbox.',
        ],
        detail: [
            {
                h: 'The banking address rule',
                p: [
                    'A dedicated, never-published address for financial accounts means that phishing sent to your normal address, claiming to be your bank, is instantly false — it arrived at the wrong door.',
                    'That is a check you can apply in one second, half-asleep, without inspecting anything.',
                ],
            },
        ],
        keys: 'email alias hide my email relay plus addressing separate email for banking spam which company leaked my email',
        terms: ['data-breach', 'phishing'],
    },
    {
        id: 'breach-check',
        title: 'Find out what has already leaked',
        glyph: '🔦',
        cat: 'accounts',
        aud: 'user',
        impact: 'medium',
        effort: 'minutes',
        lede: 'You are probably already in several breaches. That is normal and not shameful — what matters is knowing which passwords are burned, and where you reused them.',
        steps: [
            'Check your addresses on a reputable breach-notification service (Have I Been Pwned is the long-standing one).',
            'Use your password manager’s built-in breach report — it can match actual stored passwords, not just addresses.',
            'Change any password that appears, **everywhere you used it**, not only on the breached site.',
            'Turn on the browser or manager warning for compromised passwords and act on it when it fires.',
            'Expect targeted phishing after a breach that quotes real details. Knowing the breach happened is what makes that message look wrong instead of convincing.',
        ],
        detail: [
            {
                h: 'Do not pay for "removal"',
                p: [
                    'Nobody can delete your data from a criminal dump. Services promising to do so are selling reassurance at best, and are sometimes a recovery scam. Spend the effort on changing the reused passwords instead.',
                ],
            },
        ],
        keys: 'have i been pwned breach check leaked password data breach check my email was my password leaked',
        terms: ['data-breach', 'credential-stuffing', 'recovery-scam'],
    },

    /* ============================================================== VERIFY == */
    {
        id: 'never-click',
        title: 'Never take the link. Go to the site yourself',
        glyph: '🚷',
        cat: 'verify',
        aud: 'user',
        impact: 'high',
        effort: 'ongoing',
        lede: 'This is the single habit that protects you from the largest number of attacks in this entire site, and it costs about eight seconds. The question is not "is this link safe?" — it is "why am I letting a stranger choose where I log in?"',
        steps: [
            'Treat every link that leads to a **login page or a payment page** as untrusted, regardless of who appears to have sent it.',
            'Close the message. Open the app from your phone’s home screen, or type the address you know, or use a bookmark you made yourself.',
            'If the alert is real, it will be waiting for you inside the app. Every genuine bank, tax office and delivery firm shows it there.',
            'If nothing is waiting for you inside the app, the message was false. You have your answer, and you never had to judge the link.',
            'Make bookmarks once, deliberately, for your bank, tax portal and main accounts. Use only those thereafter.',
        ],
        detail: [
            {
                h: 'Yes, links in email are normal — this is narrower than it sounds',
                p: [
                    'You do not have to live link-free. Read the newsletter, open the article, follow the tracking page. The rule applies to the specific moment where a link asks you to **prove who you are or move money**.',
                    'Everything expensive happens in that moment. Nothing is lost by arriving there under your own steam.',
                ],
            },
            {
                h: 'Why "check the link carefully" is not good enough on its own',
                p: [
                    'Homograph domains are visually identical. Open redirects start with a real, trusted domain. Shortened links reveal nothing. On a phone the address bar truncates the middle, which is exactly where the deception lives.',
                    'Checking is a good second layer. Not needing to check is the first one.',
                ],
            },
            {
                h: 'The version for the office',
                p: [
                    'Same rule, one addition: report it. A message you merely delete protects one person; a message you report protects everyone else who got it, and lets the security team pull it from other mailboxes before somebody clicks.',
                ],
            },
        ],
        keys: 'should i click links in email never click links go to the site directly type the address bookmark bank instead of link is it safe to click',
        terms: ['phishing', 'domain-name', 'open-redirect', 'homograph', 'typosquatting'],
    },
    {
        id: 'check-a-site',
        title: 'Check whether a website is real before you trust it',
        glyph: '🔎',
        cat: 'verify',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'There is one check that matters and a handful that support it. The one that matters is the domain — the part immediately before the first single slash. Everything else in a web address can be made to say anything.',
        steps: [
            'Find the domain: read the address backwards from the first single `/` to the `://`. Take the **last two labels** of that. In `login.bank.secure-verify.io/eu`, the site is `secure-verify.io`, not `bank`.',
            'Ask whether that exact domain is the one you already knew. If you are not sure, you are not sure — leave and navigate there yourself.',
            'Watch for a brand name used as a *word* rather than as the domain: `paypal-support.help`, `bank.login-eu.com`, `amazon.delivery-track.co`.',
            'Check the padlock means nothing more than encryption. Phishing sites have padlocks. It proves the connection is private, not that the recipient is honest.',
            'For a shop, look for a real company name, address, registration or VAT number, and a phone number that answers. Then search that company name plus "reviews" and "scam".',
            'Check the domain’s age with a WHOIS lookup. A "20 years in business" shop on a six-week-old domain has answered your question.',
            'Pay by card, never by bank transfer or crypto — that alone converts most fake-shop losses into a chargeback.',
        ],
        detail: [
            {
                h: 'Read the address the way a computer does',
                p: [
                    'Everything before an `@` in a URL is ignored by the browser. `https://www.yourbank.com@evil.example/login` goes to `evil.example`.',
                    'Everything after the first single `/` is chosen freely by whoever owns the domain. A path can say `/secure/verify/yourbank` and mean nothing.',
                    'Subdomains are free and infinite. Anyone owning `evil.example` can create `www.yourbank.com.evil.example`.',
                    'So: last two labels before the first single slash. That is the whole test.',
                ],
            },
            {
                h: 'Signals that are worth something',
                p: [
                    'A domain you have used before and bookmarked. A payment page hosted by a recognised processor. A company traceable in a public business register. Independent reviews on a site the shop does not control. A physical address that is not a residential flat or a mail drop.',
                ],
            },
            {
                h: 'Signals that are worth nothing',
                p: [
                    'A padlock. A professional design — templates are free and stolen catalogues are common. Five-star reviews on the site itself. A "trust badge" image, which is just an image. A live chat window. A copied privacy policy.',
                ],
            },
        ],
        keys: 'how to check if a website is real fake website check is this site legit verify a website domain check padlock whois new domain safe shopping',
        terms: ['typosquatting', 'homograph', 'padlock', 'domain-name', 'fake-shop', 'open-redirect'],
    },
    {
        id: 'check-a-link',
        title: 'Inspect a link when you really must',
        glyph: '🔗',
        cat: 'verify',
        aud: 'user',
        impact: 'medium',
        effort: 'minutes',
        lede: 'Sometimes you need to know where something goes without going there. Here is how to look, and where looking stops being reliable.',
        steps: [
            'On a computer, **hover** and read the status bar at the bottom left. Do not click.',
            'On a phone, **long-press** the link to preview the full address, then dismiss it.',
            'Apply the domain test: last two labels before the first single slash.',
            'Read all the way to the end for `?url=`, `?redirect=`, `?next=` — a trusted domain can be a springboard.',
            'Expand shortened links with a preview service, or by adding `+` to some shorteners, before deciding.',
            'If you see `xn--` anywhere in the domain, stop. That is a non-Latin lookalike.',
            'When it still matters: do not resolve the doubt. Go to the site yourself instead.',
        ],
        detail: [
            {
                h: 'Where inspection fails',
                p: [
                    'A QR code cannot be inspected at all until your camera shows the preview — and many people tap through that preview without reading it.',
                    'HTML email can display one address and link to another. What you see is decoration; what you hover is the truth.',
                    'A link that is genuinely fine today can be repointed tomorrow. Compromised legitimate sites are used precisely because they pass every check.',
                ],
            },
            {
                h: 'Uploading to a scanner',
                p: [
                    'Public scanning services are useful, but treat anything you submit as published — never upload a document containing personal or company data. Submit the URL, not the file, unless you accept that consequence.',
                ],
            },
        ],
        keys: 'check a link before clicking hover over link preview link shortened url expand bitly is this link safe long press link',
        terms: ['open-redirect', 'homograph', 'domain-name', 'quishing'],
    },
    {
        id: 'verify-a-human',
        title: 'Verify the person, not the message',
        glyph: '📞',
        cat: 'verify',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'Caller ID is forged for free. Display names are typed by the sender. Voices are cloned from a voicemail greeting. Video can be synthesised live. None of the things people use to recognise each other still work, so identity has to be confirmed on a channel you choose.',
        steps: [
            'Hang up, or close the message. This is never rude and always allowed.',
            'Find the number yourself — the back of your bank card, the official app, a statement, a bookmark. **Never** the number in the message, and never one from a search engine.',
            'Call back on that number. If they told you to expect a call from a specific extension, ignore it.',
            'On a landline, wait sixty seconds or use a different phone: some old lines stay open after you hang up, and a fraudster can play a dial tone.',
            'For family emergencies, ask the agreed code word, or a question only they could answer that is not on any social media.',
            'For a payment or bank-detail change at work, always call the known contact on a number **already on file** — never one from the email requesting the change.',
        ],
        detail: [
            {
                h: 'Three things no real organisation will ever do',
                p: [
                    'Ask for your full password, PIN, or a one-time code.',
                    'Ask you to move money to a "safe account", or to withdraw cash and hand it to a courier.',
                    'Ask you to install remote-access software so they can "show you the problem".',
                    'Any one of these ends the conversation. You do not need to be polite about it, and you do not need to be certain about anything else.',
                ],
            },
            {
                h: 'The secrecy tell',
                p: [
                    '"Do not tell the bank staff why you are withdrawing." "This is a confidential investigation." "Do not discuss this with colleagues." Real organisations do not need you to hide what you are doing from other honest people. Secrecy is not a security measure; it is an isolation tactic.',
                ],
            },
        ],
        keys: 'verify caller hang up and call back is this really my bank fake call check identity code word call back official number',
        terms: ['vishing', 'deepfake', 'spoofing', 'code-word'],
    },
    {
        id: 'qr-discipline',
        title: 'Treat a QR code as an unreadable link',
        glyph: '🔳',
        cat: 'verify',
        aud: 'user',
        impact: 'medium',
        effort: 'minutes',
        lede: 'A QR code is a link you are physically incapable of reading. That is the entire problem, and it is why criminals moved to them.',
        steps: [
            'Before tapping, **read the address your camera previews.** Every modern phone shows it; almost nobody looks.',
            'Refuse QR codes that lead to login or payment pages. Pay through the merchant’s own app or a number you already had.',
            'In public, feel the code: a sticker over printed material lifts at the edge. Parking meters and EV chargers are the classic targets.',
            'Ignore QR codes inside emails and PDFs entirely. There is no honest reason to put one in a message already on a screen.',
            'Do not use "QR scanner" apps from an app store — your built-in camera is safer and does not sell your scan history.',
        ],
        detail: [
            {
                h: 'Why work email is full of them now',
                p: [
                    'A QR code in an email defeats the company link scanner (there is no link to scan) and moves you to a personal phone that has none of the office’s protections. If a work email asks you to scan a code to "re-enrol your MFA", that is the attack almost every time. Report it.',
                ],
            },
        ],
        keys: 'qr code safety scan qr safely quishing parking meter qr sticker qr in email is it safe to scan qr codes',
        terms: ['quishing', 'aitm'],
    },

    /* =============================================================== MONEY == */
    {
        id: 'virtual-cards',
        title: 'Pay unfamiliar shops with a card number that isn’t yours',
        glyph: '🎫',
        cat: 'money',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'Yes — this exists, it is free with most modern banks, and it is the closest thing to a cheat code in personal security. A virtual card number is a real, working number that is not your card. If the shop turns out to be fake, or is breached in two years, the number is worthless and your actual card never has to be cancelled.',
        steps: [
            'Look in your banking app for **virtual card**, **disposable card**, **single-use card** or **merchant-locked card**. Many mainstream banks and most fintechs have one.',
            'If yours does not, a dedicated virtual-card provider or a fintech account funded per purchase does the same job.',
            'Generate a fresh number for each unfamiliar shop, each free trial, and each subscription you expect to be difficult to cancel.',
            'Set a spending cap close to the purchase amount, and an expiry if offered.',
            'Freeze or delete the number the moment the order arrives.',
            'For everyday, trusted shops use **Apple Pay, Google Pay or Click to Pay** — these send a device token, so the merchant never sees your real number either.',
            'Never pay an unfamiliar seller by bank transfer, crypto, or "friends and family". Those have no reversal mechanism at all.',
        ],
        detail: [
            {
                h: 'What it does and does not protect',
                p: [
                    '**Protects against:** the shop being a fraud, the shop being breached later, card details skimmed from that merchant, a subscription that refuses to stop billing, and the general nuisance of your primary card being reissued every time some retailer loses a database.',
                    '**Does not protect against:** you being tricked into paying the wrong person on purpose — the payment is still authorised. It also does not help with bank transfers, which is why the card matters in the first place.',
                ],
            },
            {
                h: 'The practical snags, so they do not surprise you',
                p: [
                    'Refunds must return to the same virtual number, so do not delete it until the return window closes — freeze it instead.',
                    'Hotels, car hire and airlines sometimes want to see the physical card at the desk. Use your real card there.',
                    'Some merchants pre-authorise a token amount; a very tight cap can cause a decline.',
                    'Recurring subscriptions need a merchant-locked card rather than a single-use one, or the second payment fails.',
                ],
            },
            {
                h: 'Card versus transfer, in one line',
                p: [
                    'A card payment has a chargeback route, a dispute process and a legal framework behind it. A bank transfer to a stranger has none. **Whenever a seller pushes you off cards, that is the fraud, not a discount.**',
                ],
            },
        ],
        keys: 'virtual card number one time use card can i use a temporary card number disposable card safe online shopping card apple pay google pay burner card',
        terms: ['vcc', 'chargeback', 'fake-shop', '3ds'],
    },
    {
        id: 'money-alarms',
        title: 'Make your money tell you when it moves',
        glyph: '🔔',
        cat: 'money',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'Most fraud losses are not stopped by cleverness; they are stopped by speed. The difference between a full reversal and a permanent loss is usually measured in hours, and you cannot be fast about something you have not noticed.',
        steps: [
            'Turn on **instant notifications for every transaction**, including small ones. Not a daily digest — every one.',
            'Set a low alert threshold. The test charge that precedes real fraud is often under €5.',
            'Enable alerts for new payees, changed limits, new device logins and address changes.',
            'Lower your online and contactless limits to what you actually need; raise them temporarily when you need more.',
            'Turn off features you never use — foreign transactions, cash advances, online gambling blocks.',
            'Save the bank’s real fraud number in your phone **now**, taken from the back of your card, so you never have to search for it under pressure.',
            'Check statements monthly for small recurring charges you never authorised.',
        ],
        detail: [
            {
                h: 'The clock, honestly',
                p: [
                    'Card fraud reported quickly is usually reimbursed. A bank transfer you were tricked into making can sometimes be recalled if you phone within minutes, occasionally within hours, and almost never after the money is moved onward. Crypto is gone at once, permanently.',
                    'This is why the alert matters more than the lock: locking after you notice is easy, noticing is the hard part.',
                ],
            },
        ],
        keys: 'transaction alerts bank notifications spot fraud early small test charge card limits fraud number save bank number',
        terms: ['card-fraud', 'apr-fraud', 'chargeback'],
    },
    {
        id: 'identity-armour',
        title: 'Lock down your identity, not just your accounts',
        glyph: '🧊',
        cat: 'money',
        aud: 'user',
        impact: 'medium',
        effort: 'an evening',
        lede: 'Cards get reissued. An identity does not. If documents have been exposed — a passport scan, an ID card, a payslip, a utility bill — the risk is credit taken out in your name, and that is fought at the credit register, not at your bank.',
        steps: [
            'Place a credit freeze, protective registration or fraud notice with the credit bureaus in your country. Names differ; ask your bank what applies where you live.',
            'Get your free credit report and read every entry. Dispute anything you do not recognise in writing.',
            'Report identity theft to the police and keep the reference number — lenders will ask for it repeatedly.',
            'Tell your bank to add a note to the account, and consider a new account number if documents were exposed.',
            'Redirect or secure your post if the address may have been used; stolen post is still a live technique.',
            'Keep a dated log of everything: who you called, when, what they said, and every reference number.',
        ],
        detail: [
            {
                h: 'What "exposed documents" actually means',
                p: [
                    'A photograph of your ID sent to a fake landlord, a copy uploaded to a fraudulent job portal, or a breach at a company that verified you. Those images are reused for months or years, because unlike a card number they cannot be cancelled.',
                    'This is also why you should never send an ID photo to anyone who contacted you first, and why watermarking a copy — "for X, on date Y, no other use" — is worth the ten seconds.',
                ],
            },
        ],
        keys: 'identity theft protect identity credit freeze cifas loans in my name passport copy stolen id documents exposed credit report',
        terms: ['credit-freeze', 'data-breach', 'doxxing'],
    },

    /* ============================================================== DEVICE == */
    {
        id: 'update-everything',
        title: 'Let everything update itself',
        glyph: '🔄',
        cat: 'device',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'Unglamorous and enormously effective. The overwhelming majority of real-world compromises use a flaw that was fixed months earlier on a device that never restarted.',
        steps: [
            'Turn on automatic updates for the operating system on every phone, tablet and computer.',
            'Restart properly at least weekly. Many updates are only finished on reboot; a laptop lid is not a restart.',
            'Update browsers and let extensions update — then remove the extensions you no longer use. An abandoned extension that changes hands is a common attack.',
            'Do not run devices past end of support. An unsupported phone or router gets no fixes at all.',
            'Replace the router your provider gave you eight years ago, or at minimum change its admin password and check its DNS settings.',
            'Only install software from the official store or the vendor’s own site — never from a search advert.',
        ],
        detail: [
            {
                h: 'The router deserves a paragraph',
                p: [
                    'It sees all your traffic and is usually the oldest, least-patched computer in the house. Change the admin password, disable remote administration from the internet, check that DNS settings are the ones you expect, and turn on WPA3 or at least WPA2 with a long passphrase.',
                    'Unexpected DNS settings on a router are the pharming attack — every device in the house then goes to the attacker’s copy of any site, no matter how carefully you type the address.',
                ],
            },
        ],
        keys: 'updates patch automatic updates restart router security old phone unsupported browser extensions update everything',
        terms: ['pharming', 'malware'],
    },
    {
        id: 'backups',
        title: 'Keep backups that ransomware cannot reach',
        glyph: '💾',
        cat: 'device',
        aud: 'user',
        impact: 'high',
        effort: 'an evening',
        lede: 'A backup that is permanently connected is not a backup — it is a second copy waiting to be encrypted alongside the first. Modern ransomware deliberately hunts attached drives, network shares and synced cloud folders before it starts.',
        steps: [
            'Follow **3-2-1**: three copies, on two different kinds of media, one of them offline or off-site.',
            'Keep at least one external drive **physically unplugged** between backups.',
            'Do not confuse cloud sync with backup: sync faithfully replicates encrypted files. Use versioning and know how to roll back.',
            'Turn on file version history on your computer, and check how far back it actually goes.',
            'Back up your phone as well — photographs are what people grieve for.',
            'Test a restore once. An untested backup is a hypothesis, not a safety net.',
        ],
        detail: [
            {
                h: 'The test nobody does',
                p: [
                    'Pick one file at random and restore it to a new location. Open it. That five-minute exercise finds the wrong folder set, the full disk and the corrupted archive — all of which are otherwise discovered on the worst possible day.',
                ],
            },
        ],
        keys: 'backup 3-2-1 ransomware backup external drive offline backup cloud sync is not backup restore test version history',
        terms: ['ransomware'],
    },
    {
        id: 'phone-lock',
        title: 'Harden the phone itself',
        glyph: '📱',
        cat: 'device',
        aud: 'user',
        impact: 'high',
        effort: 'minutes',
        lede: 'Your phone is the second factor for everything you own. A thief who watches you type a four-digit code in a bar and then takes the handset can own your entire life within twenty minutes — that specific attack is now common enough to have its own name in police statistics.',
        steps: [
            'Use a **six-digit or alphanumeric** passcode, not four digits, and cover your hand when you type it.',
            'Turn on the option that requires biometrics (not the passcode) to change account settings, where your phone offers it — iOS Stolen Device Protection and equivalents.',
            'Set a SIM PIN so a stolen handset’s SIM cannot be moved into another phone.',
            'Add a port-out PIN with your carrier.',
            'Hide message previews on the lock screen — one-time codes should not be readable through the glass.',
            'Enable Find My / Find My Device with remote wipe, and know the password to use it from someone else’s device.',
            'Do not store passwords, PINs or recovery codes in a note or a photo of a piece of paper.',
        ],
        detail: [
            {
                h: 'Why the passcode matters more than the fingerprint',
                p: [
                    'Biometrics protect the unlock. The passcode protects everything else: it can usually reset the account password, disable Find My, remove other factors and add the thief’s own face. Watching it typed once is the whole attack.',
                ],
            },
        ],
        keys: 'phone security passcode stolen phone sim pin lock screen codes visible find my remote wipe stolen device protection',
        terms: ['sim-swap', 'shoulder-surfing', 'stalkerware'],
    },
    {
        id: 'public-networks',
        title: 'Use public Wi-Fi and public chargers sensibly',
        glyph: '📶',
        cat: 'device',
        aud: 'user',
        impact: 'medium',
        effort: 'minutes',
        lede: 'This risk is real but widely overstated, and the overstatement leads people to buy the wrong thing. Encrypted connections mean a café network cannot read your banking session. What it can still do is show you a convincing sign-in page and ask you to install something.',
        steps: [
            'Prefer your mobile data, or a personal hotspot, for anything financial. It is simpler than any other advice here.',
            'Never install a certificate, profile or app that a Wi-Fi portal asks for. That, not eavesdropping, is the actual attack.',
            'Never "log in with your email password" to get online.',
            'Turn off automatic joining of open networks so your phone does not silently reconnect to a spoofed name later.',
            'Use a data-blocker cable or your own charger with public USB ports; refuse any "Trust this computer?" prompt.',
            'A VPN hides your traffic from the network and its owner. It does not protect you from phishing, malware or a fake login page — and a free VPN is a business that sells something else.',
        ],
        detail: [
            {
                h: 'What the risk actually is now',
                p: [
                    'Nearly all traffic is encrypted, so passive snooping yields very little. The realistic threats on an untrusted network are: a captive portal that phishes, a prompt to install a root certificate, and a spoofed network name your device joins automatically because you connected to the real one once.',
                    'All three are defeated by the same instinct: on someone else’s network, do not install anything and do not log in anywhere new.',
                ],
            },
        ],
        keys: 'public wifi safe vpn needed airport wifi hotel wifi coffee shop wifi juice jacking usb charging captive portal',
        terms: ['evil-twin', 'juice-jacking', 'vpn'],
    },

    /* ============================================================== PEOPLE == */
    {
        id: 'protect-elders',
        title: 'Protect the people being targeted hardest',
        glyph: '👵',
        cat: 'people',
        aud: 'user',
        impact: 'high',
        effort: 'an evening',
        lede: 'Older relatives are deliberately targeted, lose more per incident, and are far less likely to tell anyone. The most powerful protection is not software — it is making it socially safe to ask, and normal to check.',
        steps: [
            'Agree a **family code word**, in person, that a caller must be able to say.',
            'Establish the rule out loud: *"nobody in this family will ever be angry with you for hanging up and calling us back."*',
            'Ask them to phone you before any unexpected payment, transfer, gift-card purchase or courier collection. Make yourself the second signature.',
            'Set up transaction alerts on their account so someone else sees the movement.',
            'Put your own number in their phone under a name they will actually look for at 8pm.',
            'Talk about specific current scams without lecturing — the courier collection, the "bank safe account", the grandchild in trouble, the fake tech-support pop-up.',
            'Never shame someone who fell for one. Shame is exactly what keeps the second, larger loss hidden.',
        ],
        detail: [
            {
                h: 'The courier scam, because it is everywhere',
                p: [
                    'A caller claiming to be from the bank or the police says the victim’s account is compromised, asks them to withdraw cash or hand over the card "for evidence", and sends someone to collect it from the door.',
                    'No bank, police force or official body will ever send someone to your home to collect cash, cards or PINs. Not once, not ever, under any circumstances. That single sentence, taught in advance, stops the whole thing.',
                ],
            },
        ],
        keys: 'protect elderly parents grandparents scam older people targeted code word courier scam family rules talk to parents about scams',
        terms: ['code-word', 'vishing', 'deepfake', 'gift-card-scam'],
    },
    {
        id: 'protect-kids',
        title: 'Prepare children and teenagers',
        glyph: '🧒',
        cat: 'people',
        aud: 'user',
        impact: 'high',
        effort: 'ongoing',
        lede: 'Teenagers face sextortion, account theft, in-game scams and money-muling. What determines the outcome is almost never technical — it is whether they believe they can tell an adult without losing their phone or their dignity.',
        steps: [
            'Say plainly and in advance: *"If anything goes wrong online, tell me. You will not be in trouble and I will not take your phone away."* Then mean it.',
            'Teach the sextortion response before it happens: **stop replying, do not pay, screenshot, block, tell an adult, report.** Paying always makes it worse.',
            'Explain money muling: being asked to receive money into their account and pass it on is a criminal offence that destroys their ability to open a bank account for years.',
            'Cover in-game scams: free-skin sites, "I will gift you if you log in here", account trading, and Discord links from strangers.',
            'Set up MFA on their game, social and email accounts together, so it is a shared thing rather than a punishment.',
            'Know your country’s reporting route for child exploitation, and the takedown services that remove intimate images of minors.',
        ],
        detail: [
            {
                h: 'Why "you will not be in trouble" is the whole control',
                p: [
                    'Sextortion of teenagers escalates over hours, and the criminals rely on shame and isolation. Cases that end quickly are almost always the ones where the young person told someone within the first hour.',
                    'Every rule you set that makes disclosure expensive — losing the phone, losing the account, being shouted at — buys the criminal more time.',
                ],
            },
        ],
        keys: 'children teenagers online safety sextortion teen game scams roblox discord scam money mule tell an adult kids accounts mfa',
        terms: ['sextortion', 'task-scam'],
    },

    /* ================================================================= ORG == */
    {
        id: 'org-identity',
        title: 'Make the identity layer phishing-resistant',
        glyph: '🛡',
        cat: 'org',
        aud: 'pro',
        impact: 'high',
        effort: 'ongoing',
        lede: 'Awareness training does not scale against modern AiTM kits, because there is nothing left for the user to notice. The controls that hold are the ones that make a stolen password or a relayed code insufficient by design.',
        steps: [
            'Roll out **phishing-resistant MFA** (FIDO2 / passkeys / certificate-based) for admins first, then all staff. Nothing else on this list matters as much.',
            'Enforce device compliance or managed-device conditional access, so a stolen token is useless from an unmanaged host.',
            'Enable token protection / continuous access evaluation so revocation is fast rather than eventual.',
            'Block legacy authentication protocols outright.',
            'Restrict user consent for third-party apps and enable an admin consent workflow.',
            'Alert on new inbox rules, new mail forwarding, new MFA method registration and new OAuth grants — these are the persistence primitives, and they are cheap to detect.',
            'Give every user a one-click **report phishing** button and make reporting visibly welcome rather than embarrassing.',
            'Set DMARC to `p=reject`, and register the obvious lookalike domains before someone else does.',
        ],
        detail: [
            {
                h: 'The four detections that earn their keep',
                p: [
                    '**New inbox rule** that deletes, archives or forwards — especially rules named with a single character, a dot or a space.',
                    '**New MFA method registered** shortly after a sign-in from an unusual location.',
                    '**OAuth consent granted** to an application with mail or file scopes and a low global consent count.',
                    '**Sign-in from an unfamiliar ASN with no failed attempts and no MFA challenge** — the signature of a replayed token.',
                ],
            },
            {
                h: 'What to stop paying for',
                p: [
                    'Punitive phishing-simulation programmes that report a click rate and nothing else. They generate resentment, teach users to distrust internal mail, and measure the wrong thing. Measure **report rate and time to report** instead — that is the number that shortens a real incident.',
                ],
            },
        ],
        keys: 'phishing resistant mfa conditional access fido2 organisation security controls dmarc reject inbox rule detection oauth consent block legacy auth',
        terms: ['aitm', 'oauth-consent', 'session-hijacking', 'spf-dkim-dmarc'],
    },
    {
        id: 'org-payments',
        title: 'Design payment fraud out of the process',
        glyph: '🏦',
        cat: 'org',
        aud: 'pro',
        impact: 'high',
        effort: 'an evening',
        lede: 'Business email compromise beats technical controls because nothing technical happens. It is defeated at the process layer, and the process is short enough to write on one page.',
        steps: [
            'Rule one: **a change of bank details is never actioned from an email.** Ever. It is verified by voice, on a number already on file from before the request.',
            'Rule two: dual authorisation for payments above a threshold, with the second approver empowered to say no to anyone, including the CEO.',
            'Rule three: written approval that urgency and secrecy are **not** grounds to bypass either rule, signed by the executive team so nobody fears the phone call.',
            'Use payee-name verification (Confirmation of Payee or equivalent) and treat a mismatch as a full stop, not a warning.',
            'Keep a supplier bank-detail register with change history, so "they have always used this account" is a fact rather than a memory.',
            'Rehearse the recall path: who calls which bank, at what number, out of hours. The window is measured in hours.',
        ],
        detail: [
            {
                h: 'Give juniors an unarguable script',
                p: [
                    '"I am required to verify any change of bank details by phone on our recorded number before processing. I will call you back on that number now." — written down, approved, and impossible to be disciplined for using.',
                    'The person who most needs this sentence is the newest member of the finance team, at 16:40 on a Friday, being pressured by someone claiming to be a director.',
                ],
            },
        ],
        keys: 'bec prevention payment process dual authorisation confirmation of payee supplier bank details verification invoice fraud controls finance',
        terms: ['bec', 'invoice-fraud', 'ceo-fraud'],
    },
    {
        id: 'org-readiness',
        title: 'Be ready before the call comes',
        glyph: '🧭',
        cat: 'org',
        aud: 'pro',
        impact: 'medium',
        effort: 'an evening',
        lede: 'In the first hour of an incident nobody reads a policy. What people use is a printed page with names, numbers and permissions on it — assembled beforehand, kept somewhere that is still readable when the network is not.',
        steps: [
            'Write a one-page **first-hour card**: who to call, in what order, with mobile numbers. Print it.',
            'Establish an out-of-band comms channel agreed in advance, on the assumption that email and chat are compromised or unavailable.',
            'Pre-authorise containment: name the people permitted to isolate a host, disable an account or pull an internet link at 3am without waiting for approval.',
            'Know your regulatory clocks before the day: GDPR is 72 hours for notifiable personal-data breaches, and sector rules may be shorter.',
            'Keep insurer, external DFIR retainer, legal counsel and law-enforcement contacts on the same card.',
            'Verify log retention actually covers the window you would need. Discovering a 7-day retention during an investigation is a specific, recurring tragedy.',
            'Run one tabletop a year and record only the questions nobody could answer. That list is the real deliverable.',
        ],
        detail: [
            {
                h: 'Things people always wish they had done',
                p: [
                    'Enabled and retained sign-in and audit logs at a tier that includes the detail they need — not the default.',
                    'Kept an accurate asset and identity inventory, so "how many admins do we have?" has an answer.',
                    'Agreed in writing who talks to press, staff, customers and the regulator, and who definitely does not.',
                    'Stored the incident plan somewhere reachable when the domain is down and the wiki is encrypted.',
                ],
            },
        ],
        keys: 'incident response readiness first hour card out of band comms tabletop log retention gdpr 72 hours dfir retainer escalation contacts',
        terms: ['tabletop', 'containment', 'chain-of-custody', 'dwell-time'],
    },
];
