#!/usr/bin/env python3
"""
Convert every PDF in ../pdf/ into a JavaScript data file the site can search.

    python tools/build.py

Writes ../data/<id>.js per document plus ../data/manifest.js, then the page
picks them up automatically. Re-run it after dropping new PDFs into ../pdf/.

Why the text gets scrubbed: the EU Publications Office PDFs carry kerning
artifacts, so extraction yields "cybersecur ity" and "REGUL A TION". The site
searches a whitespace-stripped copy to see through that, so all this script has
to do is collapse whitespace and hand over faithful page text.
"""

import glob
import json
import os
import re
import sys
from datetime import date

try:
    from pypdf import PdfReader
except ImportError:
    sys.exit("pypdf is missing.  pip install pypdf")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PDF_DIR = os.path.join(ROOT, "pdf")
DATA_DIR = os.path.join(ROOT, "data")

# Nice human titles keyed by filename. Anything not listed falls back to the
# PDF's own /Title, then to the filename.
TITLES = {
    "OJ_L_202402847_EN_TXT.pdf": (
        "Regulation (EU) 2024/2847 — Cyber Resilience Act",
        "The Cyber Resilience Act itself: horizontal cybersecurity requirements "
        "for products with digital elements.",
    ),
    "C_2026_5252_1_EN_ACT_part1_v3_Q5FcQmYjJYGQXCLONQKTnHkenw_131455 (1).pdf": (
        "C(2026) 5252 final — Communication to the Commission",
        "Cover act approving the content of the draft CRA guidance.",
    ),
    "C_2026_5252_1_EN_annexe_acte_autonome_cp_part1_v3_kXuCPwXXxAuG8Uj44Ar0o2Vros_131456 (1).pdf": (
        "C(2026) 5252 final ANNEX — Commission guidance on the CRA",
        "The guidance annex: how the Commission reads and applies Regulation "
        "(EU) 2024/2847 in practice.",
    ),
}


def slugify(name):
    s = re.sub(r"\.pdf$", "", name, flags=re.I)
    s = re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-").lower()
    s = re.sub(r"-+", "-", s)
    return s[:60] or "doc"


def clean(text):
    """Collapse whitespace runs but keep the characters themselves intact."""
    text = text.replace("\u00ad", "")            # soft hyphen
    text = text.replace("\ufb01", "fi").replace("\ufb02", "fl")
    text = re.sub(r"[ \t\r\f\v\u00a0]+", " ", text)
    text = re.sub(r"\s*\n\s*", " ", text)
    return text.strip()


def js_string(s):
    """JSON encodes safely for embedding in JS, including </script> guards."""
    return json.dumps(s, ensure_ascii=False).replace("</", "<\\/")


def build():
    if not os.path.isdir(PDF_DIR):
        sys.exit(f"No pdf folder at {PDF_DIR}")
    os.makedirs(DATA_DIR, exist_ok=True)

    pdfs = sorted(glob.glob(os.path.join(PDF_DIR, "*.pdf")))
    if not pdfs:
        sys.exit("No PDFs found in " + PDF_DIR)

    manifest = []
    seen_ids = set()

    for path in pdfs:
        name = os.path.basename(path)
        reader = PdfReader(path)
        meta = reader.metadata or {}

        doc_id = slugify(name)
        while doc_id in seen_ids:
            doc_id += "-2"
        seen_ids.add(doc_id)

        title, blurb = TITLES.get(name, (None, ""))
        if not title:
            title = (meta.get("/Title") or "").strip() or re.sub(r"\.pdf$", "", name, flags=re.I)

        pages = []
        chars = 0
        for i, page in enumerate(reader.pages, 1):
            try:
                text = clean(page.extract_text() or "")
            except Exception as exc:                     # a damaged page must not kill the build
                print(f"    ! page {i} failed: {exc}")
                text = ""
            chars += len(text)
            pages.append(text)

        empty = sum(1 for p in pages if not p.strip())
        out = os.path.join(DATA_DIR, doc_id + ".js")
        with open(out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("/* Generated by tools/build.py. Do not edit by hand. */\n")
            fh.write("window.PDF_SEARCH_DATA = window.PDF_SEARCH_DATA || {};\n")
            fh.write(f"window.PDF_SEARCH_DATA[{js_string(doc_id)}] = [\n")
            for text in pages:
                fh.write(js_string(text) + ",\n")
            fh.write("];\n")

        manifest.append({
            "id": doc_id,
            "file": name,
            "title": title,
            "blurb": blurb,
            "pages": len(pages),
            "chars": chars,
            "emptyPages": empty,
            "bytes": os.path.getsize(path),
            "added": date.today().isoformat(),
        })
        flag = f"  ({empty} empty pages — scanned images?)" if empty else ""
        print(f"  {title[:58]:<60} {len(pages):>4} pages  {chars:>8,} chars{flag}")

    with open(os.path.join(DATA_DIR, "manifest.js"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("/* Generated by tools/build.py. Do not edit by hand. */\n")
        fh.write("window.PDF_SEARCH_MANIFEST = ")
        fh.write(json.dumps(manifest, ensure_ascii=False, indent=2).replace("</", "<\\/"))
        fh.write(";\n")

    total = sum(d["chars"] for d in manifest)
    print(f"\n{len(manifest)} documents, {sum(d['pages'] for d in manifest)} pages, {total:,} chars indexed.")


if __name__ == "__main__":
    build()
